use crate::engine::tweak::*;

pub fn tweaks() -> Vec<TweakDefinition> {
    vec![
        TweakDefinition {
            id: "disable_tips_suggestions".into(),
            name: "Disable Tips & Suggestions".into(),
            description: "Stops Windows from showing tips, tricks, and suggestion notifications.".into(),
            why_it_helps: "These popups interrupt your workflow and gaming sessions with unhelpful 'did you know' messages. Disabling them gives you a cleaner, quieter experience.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Fewer popup interruptions".into(),
            when_not_to_use: "If you're new to Windows and find the tips helpful.".into(),
            how_to_undo: "Re-enable in Windows Settings > System > Notifications.".into(),
            tags: vec!["annoyance".into(), "notifications".into(), "tips".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager".into(),
                    name: "SoftLandingEnabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager".into(),
                    name: "SubscribedContent-338389Enabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager".into(),
                    name: "SubscribedContent-310093Enabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
        TweakDefinition {
            id: "disable_finish_setup_nag".into(),
            name: "Disable 'Finish Setting Up' Nag".into(),
            description: "Stops the recurring 'Let's finish setting up your device' prompt.".into(),
            why_it_helps: "This nag screen appears periodically urging you to set up OneDrive, link a phone, etc. It's persistent and annoying if you've already configured things the way you want.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Removes recurring setup nag screens".into(),
            when_not_to_use: "If you haven't finished setting up all Windows features.".into(),
            how_to_undo: "Delete the ScoobeSystemSettingEnabled registry value.".into(),
            tags: vec!["annoyance".into(), "setup".into(), "nag".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\UserProfileEngagement".into(),
                    name: "ScoobeSystemSettingEnabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager".into(),
                    name: "SubscribedContent-310093Enabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
        TweakDefinition {
            id: "disable_web_search".into(),
            name: "Disable Start Menu Web Search".into(),
            description: "Stops the Start Menu from searching the web via Bing when you type.".into(),
            why_it_helps: "When you search in the Start Menu, Windows sends your query to Bing and shows web results. This slows down local searches and sends your queries to Microsoft. Disabling it makes Start Menu search fast and local-only.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Faster Start Menu search, no web results clutter".into(),
            when_not_to_use: "If you use the Start Menu to search the web frequently.".into(),
            how_to_undo: "Delete the DisableSearchBoxSuggestions and BingSearchEnabled registry values.".into(),
            tags: vec!["annoyance".into(), "search".into(), "privacy".into(), "bing".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Policies\Microsoft\Windows\Explorer".into(),
                    name: "DisableSearchBoxSuggestions".into(),
                    desired_value: RegistryValueData::Dword(1),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Search".into(),
                    name: "BingSearchEnabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
        TweakDefinition {
            id: "disable_widgets".into(),
            name: "Disable Widgets".into(),
            description: "Removes the Widgets panel and its taskbar button.".into(),
            why_it_helps: "The Widgets panel runs a background Edge WebView process that consumes RAM and CPU. It opens accidentally when you hover near the taskbar edge. Disabling it frees resources and removes a distraction.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Frees ~100-200MB RAM, removes accidental hover popup".into(),
            when_not_to_use: "If you actively use the Widgets panel for news or weather.".into(),
            how_to_undo: "Re-enable in Taskbar settings.".into(),
            tags: vec!["annoyance".into(), "widgets".into(), "ram".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced".into(),
                    name: "TaskbarDa".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
        TweakDefinition {
            id: "disable_copilot".into(),
            name: "Disable Copilot".into(),
            description: "Disables Windows Copilot and removes it from the taskbar.".into(),
            why_it_helps: "Copilot runs background processes and takes up taskbar space. If you don't use it, disabling it frees up resources and declutters your taskbar.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Cleaner taskbar, less background resource usage".into(),
            when_not_to_use: "If you use Windows Copilot for AI assistance.".into(),
            how_to_undo: "Re-enable in Windows Settings > Personalization > Taskbar.".into(),
            tags: vec!["annoyance".into(), "copilot".into(), "ai".into(), "taskbar".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced".into(),
                    name: "ShowCopilotButton".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Policies\Microsoft\Windows\WindowsCopilot".into(),
                    name: "TurnOffWindowsCopilot".into(),
                    desired_value: RegistryValueData::Dword(1),
                },
            ],
        },
        TweakDefinition {
            id: "disable_sticky_keys".into(),
            name: "Disable Sticky Keys Prompt".into(),
            description: "Prevents the Sticky Keys dialog from appearing when you press Shift 5 times.".into(),
            why_it_helps: "In games that use Shift heavily (sprinting, crouching), the Sticky Keys prompt can pop up and minimize your game. This is one of the most common gaming annoyances on Windows.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Prevents game-breaking keyboard popups".into(),
            when_not_to_use: "If you rely on Sticky Keys for accessibility.".into(),
            how_to_undo: "Re-enable in Windows Settings > Accessibility > Keyboard.".into(),
            tags: vec!["annoyance".into(), "gaming".into(), "keyboard".into(), "accessibility".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"Control Panel\Accessibility\StickyKeys".into(),
                name: "Flags".into(),
                desired_value: RegistryValueData::String("506".into()),
            }],
        },
        TweakDefinition {
            id: "disable_filter_keys".into(),
            name: "Disable Filter Keys Prompt".into(),
            description: "Prevents the Filter Keys dialog from appearing when holding Right Shift.".into(),
            why_it_helps: "Holding Right Shift for 8 seconds triggers a Filter Keys prompt that can interrupt gameplay. This tweak disables the prompt while keeping Filter Keys available if manually enabled.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Prevents game-breaking keyboard popups".into(),
            when_not_to_use: "If you rely on Filter Keys for accessibility.".into(),
            how_to_undo: "Re-enable in Windows Settings > Accessibility > Keyboard.".into(),
            tags: vec!["annoyance".into(), "gaming".into(), "keyboard".into(), "accessibility".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"Control Panel\Accessibility\Keyboard Response".into(),
                name: "Flags".into(),
                desired_value: RegistryValueData::String("122".into()),
            }],
        },
        TweakDefinition {
            id: "disable_notification_sounds".into(),
            name: "Disable Notification Sounds".into(),
            description: "Silences all Windows notification sounds.".into(),
            why_it_helps: "Notification sounds play over game audio and can be distracting during gameplay or focused work. Visual notifications still appear.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No more surprise notification dings during gaming".into(),
            when_not_to_use: "If you rely on audio cues for important notifications.".into(),
            how_to_undo: "Re-enable notification sounds in Windows Settings > System > Notifications.".into(),
            tags: vec!["annoyance".into(), "audio".into(), "notifications".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings".into(),
                name: "NOC_GLOBAL_SETTING_ALLOW_TOASTS_ABOVE_LOCK".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_autoplay".into(),
            name: "Disable AutoPlay".into(),
            description: "Stops Windows from automatically opening media when you plug in USB drives.".into(),
            why_it_helps: "AutoPlay is a minor security risk and interrupts your workflow when you plug in external drives. Most people prefer to open files manually.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Prevents unwanted popups when plugging in USB".into(),
            when_not_to_use: "If you want media to start automatically when inserting discs or drives.".into(),
            how_to_undo: "Re-enable in Windows Settings > Devices > AutoPlay.".into(),
            tags: vec!["annoyance".into(), "usb".into(), "security".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers".into(),
                name: "DisableAutoplay".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "disable_explorer_ads".into(),
            name: "Disable File Explorer Ads".into(),
            description: "Removes OneDrive and other promotional suggestions from File Explorer.".into(),
            why_it_helps: "Windows shows sync provider notifications and suggestions in File Explorer, which are essentially ads. Removing them gives you a cleaner file browsing experience.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Cleaner File Explorer, no promotional popups".into(),
            when_not_to_use: "If you use OneDrive sync status notifications in Explorer.".into(),
            how_to_undo: "Re-enable in File Explorer > View > Options > Show sync provider notifications.".into(),
            tags: vec!["annoyance".into(), "ads".into(), "explorer".into(), "onedrive".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced".into(),
                name: "ShowSyncProviderNotifications".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_lock_screen_tips".into(),
            name: "Disable Lock Screen Tips & Ads".into(),
            description: "Removes fun facts, tips, and tricks from the Windows lock screen.".into(),
            why_it_helps: "The lock screen shows rotating tips and suggestions from Microsoft. These are promotional content disguised as helpful tips. Disabling them gives you a clean lock screen.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Clean lock screen without promotional content".into(),
            when_not_to_use: "If you enjoy the rotating tips and facts on the lock screen.".into(),
            how_to_undo: "Re-enable in Windows Settings > Personalization > Lock screen.".into(),
            tags: vec!["annoyance".into(), "ads".into(), "lock-screen".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager".into(),
                    name: "RotatingLockScreenOverlayEnabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager".into(),
                    name: "SubscribedContent-338387Enabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
        TweakDefinition {
            id: "disable_suggested_apps".into(),
            name: "Disable Suggested Apps in Start Menu".into(),
            description: "Removes app suggestions and promotions from the Start Menu.".into(),
            why_it_helps: "Windows shows 'suggested' apps (ads) in the Start Menu for apps you haven't installed. These take up space and are essentially advertisements.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Cleaner Start Menu without app promotions".into(),
            when_not_to_use: "If you want app discovery suggestions in the Start Menu.".into(),
            how_to_undo: "Re-enable in Windows Settings > Personalization > Start.".into(),
            tags: vec!["annoyance".into(), "ads".into(), "start-menu".into(), "bloatware".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager".into(),
                    name: "SubscribedContent-338388Enabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager".into(),
                    name: "SystemPaneSuggestionsEnabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager".into(),
                    name: "OemPreInstalledAppsEnabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager".into(),
                    name: "PreInstalledAppsEnabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
        TweakDefinition {
            id: "reduce_telemetry".into(),
            name: "Reduce Telemetry (Safe Level)".into(),
            description: "Sets Windows telemetry to the minimum level allowed.".into(),
            why_it_helps: "Windows sends diagnostic data to Microsoft in the background. Setting it to the minimum 'Required' level reduces network traffic and background CPU usage without breaking any features.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Less background data collection, slightly reduced network usage".into(),
            when_not_to_use: "If you want to help Microsoft improve Windows through diagnostics.".into(),
            how_to_undo: "Set telemetry to Full in Windows Settings > Privacy > Diagnostics & feedback.".into(),
            tags: vec!["annoyance".into(), "privacy".into(), "telemetry".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKLM,
                    path: r"SOFTWARE\Policies\Microsoft\Windows\DataCollection".into(),
                    name: "AllowTelemetry".into(),
                    desired_value: RegistryValueData::Dword(1),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKLM,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection".into(),
                    name: "MaxTelemetryAllowed".into(),
                    desired_value: RegistryValueData::Dword(1),
                },
            ],
        },
        TweakDefinition {
            id: "disable_feedback_prompts".into(),
            name: "Disable Feedback Prompts".into(),
            description: "Stops Windows from asking you for feedback about features.".into(),
            why_it_helps: "Windows periodically asks 'How likely are you to recommend this feature?' These prompts interrupt your workflow and are not useful for most users.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No more 'rate this feature' interruptions".into(),
            when_not_to_use: "If you want to provide feedback to Microsoft about Windows features.".into(),
            how_to_undo: "Delete the NumberOfSIUFInPeriod registry value.".into(),
            tags: vec!["annoyance".into(), "feedback".into(), "popups".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Siuf\Rules".into(),
                name: "NumberOfSIUFInPeriod".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "clean_taskbar".into(),
            name: "Clean Up Taskbar".into(),
            description: "Hides the search box, task view button, and chat icon from the taskbar.".into(),
            why_it_helps: "These taskbar elements take up space and can be accidentally clicked. You can still access Search with the Windows key, and Task View with Win+Tab.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Cleaner, less cluttered taskbar".into(),
            when_not_to_use: "If you use the search box, task view, or chat features regularly.".into(),
            how_to_undo: "Re-enable items in Taskbar settings (right-click taskbar).".into(),
            tags: vec!["annoyance".into(), "taskbar".into(), "ui".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Search".into(),
                    name: "SearchboxTaskbarMode".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced".into(),
                    name: "ShowTaskViewButton".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced".into(),
                    name: "TaskbarMn".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
        TweakDefinition {
            id: "disable_start_recommended".into(),
            name: "Disable Recommended Content in Start Menu".into(),
            description: "Removes the 'Recommended' section content from the Windows 11 Start Menu.".into(),
            why_it_helps: "The Recommended section shows recently opened files and app suggestions that clutter the Start Menu. Disabling it gives you a cleaner, more focused Start Menu layout.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Cleaner Start Menu without recommended content".into(),
            when_not_to_use: "If you use the Recommended section to quickly access recent files.".into(),
            how_to_undo: "Delete Start_IrisRecommendations from HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced.".into(),
            tags: vec!["annoyance".into(), "start-menu".into(), "recommended".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced".into(),
                name: "Start_IrisRecommendations".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "hide_chat_taskbar".into(),
            name: "Hide Chat Icon from Taskbar".into(),
            description: "Removes the Microsoft Teams Chat icon from the taskbar.".into(),
            why_it_helps: "The Chat icon launches Microsoft Teams, which many users don't use. It takes up taskbar space and can be accidentally clicked. Hiding it declutters your taskbar.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Removes Teams Chat icon from taskbar".into(),
            when_not_to_use: "If you actively use Microsoft Teams Chat from the taskbar.".into(),
            how_to_undo: "Re-enable in Taskbar settings > Taskbar items > Chat.".into(),
            tags: vec!["annoyance".into(), "taskbar".into(), "teams".into(), "chat".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced".into(),
                name: "TaskbarMn".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "hide_search_highlights".into(),
            name: "Hide Search Highlights".into(),
            description: "Disables the search highlights and trending content in Windows Search.".into(),
            why_it_helps: "Search highlights show trending news, images, and web content in the search box. This is distracting and slows down the search experience by loading web content when you just want to find local files and apps.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Faster, cleaner search without web content clutter".into(),
            when_not_to_use: "If you enjoy seeing trending content and search highlights.".into(),
            how_to_undo: "Set IsDynamicSearchBoxEnabled back to 1 in the registry.".into(),
            tags: vec!["annoyance".into(), "search".into(), "highlights".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\SearchSettings".into(),
                name: "IsDynamicSearchBoxEnabled".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_startup_sound".into(),
            name: "Disable Windows Startup Sound".into(),
            description: "Silences the Windows startup chime that plays when you boot up.".into(),
            why_it_helps: "The startup sound is unnecessary and can be annoying, especially if you boot your PC late at night or in a quiet environment. Disabling it makes boot-up silent.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Silent startup — no more boot chime".into(),
            when_not_to_use: "If you like the Windows startup sound as an audio confirmation of boot.".into(),
            how_to_undo: "Re-enable the startup sound in Control Panel > Sound > Sounds tab > select a scheme.".into(),
            tags: vec!["annoyance".into(), "audio".into(), "startup".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"AppEvents\Schemes".into(),
                name: "".into(),
                desired_value: RegistryValueData::String("".into()),
            }],
        },
        TweakDefinition {
            id: "disable_toggle_keys".into(),
            name: "Disable Toggle Keys Shortcut Prompt".into(),
            description: "Prevents the Toggle Keys sound prompt when pressing Num Lock for 5 seconds.".into(),
            why_it_helps: "Holding Num Lock for 5 seconds triggers a Toggle Keys prompt that can interrupt gameplay. This tweak disables the keyboard shortcut while keeping Toggle Keys available if manually enabled.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Prevents game-breaking keyboard popups".into(),
            when_not_to_use: "If you rely on Toggle Keys sounds for accessibility.".into(),
            how_to_undo: "Re-enable in Windows Settings > Accessibility > Keyboard.".into(),
            tags: vec!["annoyance".into(), "gaming".into(), "keyboard".into(), "accessibility".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"Control Panel\Accessibility\ToggleKeys".into(),
                name: "Flags".into(),
                desired_value: RegistryValueData::String("58".into()),
            }],
        },
        TweakDefinition {
            id: "disable_consumer_experience".into(),
            name: "Disable Consumer Experience Features".into(),
            description: "Prevents Windows from silently installing promoted apps and content.".into(),
            why_it_helps: "Microsoft Cloud Content features can silently install suggested apps like Candy Crush, Spotify, and other promoted software. Disabling this stops unwanted app installations and Start Menu clutter.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Stops silent installation of promoted apps".into(),
            when_not_to_use: "If you want Microsoft to suggest and install apps for you.".into(),
            how_to_undo: "Delete DisableWindowsConsumerFeatures from HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent.".into(),
            tags: vec!["annoyance".into(), "bloatware".into(), "ads".into(), "apps".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Policies\Microsoft\Windows\CloudContent".into(),
                name: "DisableWindowsConsumerFeatures".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "hide_recently_added_apps".into(),
            name: "Hide Recently Added Apps in Start".into(),
            description: "Hides the 'Recently added' section at the top of the Start Menu app list.".into(),
            why_it_helps: "The 'Recently added' section pushes your pinned and alphabetical apps down, making the Start Menu less predictable. Hiding it keeps a consistent layout.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Cleaner Start Menu app list without recently-added clutter".into(),
            when_not_to_use: "If you install apps frequently and want quick access to newly added ones.".into(),
            how_to_undo: "Delete HideRecentlyAddedApps from HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\Explorer.".into(),
            tags: vec!["annoyance".into(), "start-menu".into(), "recent".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Policies\Microsoft\Windows\Explorer".into(),
                name: "HideRecentlyAddedApps".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "disable_get_more_windows".into(),
            name: "Disable 'Get Even More Out of Windows' Prompts".into(),
            description: "Stops Microsoft from showing prompts to use more Windows features.".into(),
            why_it_helps: "Windows periodically shows full-screen or notification prompts urging you to try OneDrive, Microsoft 365, or link your phone. These are disruptive and feel like advertisements.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No more upsell prompts from Microsoft".into(),
            when_not_to_use: "If you want to discover new Windows features through these prompts.".into(),
            how_to_undo: "Set SubscribedContent-310093Enabled back to 1 in the registry.".into(),
            tags: vec!["annoyance".into(), "ads".into(), "nag".into(), "upsell".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager".into(),
                name: "SubscribedContent-310093Enabled".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "simplify_context_menu".into(),
            name: "Restore Classic Context Menu".into(),
            description: "Replaces the Windows 11 truncated context menu with the full classic one.".into(),
            why_it_helps: "Windows 11's new context menu hides most options behind a 'Show more options' click, adding an extra step to common tasks like Extract, Open With, or third-party app actions. Restoring the classic menu shows everything in one click.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: true,
            reversible: true,
            impact_estimate: "Full context menu in one click instead of two".into(),
            when_not_to_use: "If you prefer the cleaner Windows 11 context menu appearance.".into(),
            how_to_undo: "Delete the CLSID key {86ca1aa0-34aa-4e8b-a509-50c905bae2a2} from HKCU\\Software\\Classes\\CLSID.".into(),
            tags: vec!["annoyance".into(), "context-menu".into(), "ui".into(), "explorer".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32".into(),
                name: "".into(),
                desired_value: RegistryValueData::String("".into()),
            }],
        },
        TweakDefinition {
            id: "disable_activity_history".into(),
            name: "Disable Activity History".into(),
            description: "Stops Windows from collecting and storing your activity history.".into(),
            why_it_helps: "Windows tracks which apps you use, files you open, and websites you browse to power Timeline and cross-device features. Disabling it reduces background data collection and improves privacy.".into(),
            category: TweakCategory::Annoyance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Reduced background tracking and data collection".into(),
            when_not_to_use: "If you use Timeline or cross-device activity sync features.".into(),
            how_to_undo: "Re-enable in Windows Settings > Privacy > Activity history.".into(),
            tags: vec!["annoyance".into(), "privacy".into(), "tracking".into(), "history".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Privacy".into(),
                    name: "TailoredExperiencesWithDiagnosticDataEnabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Privacy".into(),
                    name: "UploadUserActivities".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
    ]
}
