use crate::engine::tweak::*;

pub fn tweaks() -> Vec<TweakDefinition> {
    vec![
        TweakDefinition {
            id: "balanced_battery_profile".into(),
            name: "Set Balanced Power Plan".into(),
            description: "Switches to the Windows Balanced power plan optimized for battery life and performance.".into(),
            why_it_helps: "The Balanced plan dynamically adjusts CPU and GPU speeds based on demand, saving significant battery compared to High Performance while still providing good responsiveness.".into(),
            category: TweakCategory::Battery,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "30-60 minutes additional battery life depending on workload".into(),
            when_not_to_use: "If you need sustained maximum performance and are plugged in.".into(),
            how_to_undo: "Switch to a different power plan in Settings > System > Power & battery.".into(),
            tags: vec!["battery".into(), "power".into(), "efficiency".into()],
            actions: vec![TweakAction::PowerPlan {
                guid: "381b4222-f694-41f0-9685-ff5bb260df2e".into(),
            }],
        },
        TweakDefinition {
            id: "reduce_screen_timeout_battery".into(),
            name: "Screen Off After 2 Minutes on Battery".into(),
            description: "Turns off the display after 2 minutes of inactivity when on battery power.".into(),
            why_it_helps: "The display is one of the largest power consumers. Turning it off quickly when idle saves significant battery without affecting your workflow.".into(),
            category: TweakCategory::Battery,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Significant battery savings during idle periods".into(),
            when_not_to_use: "If you frequently read or reference content on screen without input.".into(),
            how_to_undo: "Settings > System > Power & battery > Screen and sleep.".into(),
            tags: vec!["battery".into(), "display".into(), "timeout".into()],
            actions: vec![TweakAction::PowerCfgSetting {
                subgroup_guid: "7516b95f-f776-4464-8c53-06167f40cc99".into(),
                setting_guid: "3c0bc021-c8a8-4e07-a973-6b14cbcb2b7e".into(),
                ac_value: None,
                dc_value: Some(120),
            }],
        },
        TweakDefinition {
            id: "reduce_sleep_timeout_battery".into(),
            name: "Sleep After 5 Minutes on Battery".into(),
            description: "Puts the computer to sleep after 5 minutes of inactivity when on battery.".into(),
            why_it_helps: "Sleep mode uses almost no power. A shorter timeout prevents the laptop from draining battery when you step away briefly.".into(),
            category: TweakCategory::Battery,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Major battery savings when laptop is left idle".into(),
            when_not_to_use: "If you run long unattended tasks on battery like downloads or renders.".into(),
            how_to_undo: "Settings > System > Power & battery > Screen and sleep.".into(),
            tags: vec!["battery".into(), "sleep".into(), "timeout".into()],
            actions: vec![TweakAction::PowerCfgSetting {
                subgroup_guid: "238c9fa8-0aad-41ed-83f4-97be242c8f20".into(),
                setting_guid: "29f6c1db-86da-48c5-9fdb-f2b67b1f44da".into(),
                ac_value: None,
                dc_value: Some(300),
            }],
        },
        TweakDefinition {
            id: "disable_bluetooth_battery".into(),
            name: "Disable Bluetooth to Save Battery".into(),
            description: "Disables Bluetooth radio to conserve battery when not in use.".into(),
            why_it_helps: "Bluetooth continuously scans for and maintains connections with devices, consuming power even when idle. Disabling it when not needed saves battery.".into(),
            category: TweakCategory::Battery,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "15-30 minutes additional battery life".into(),
            when_not_to_use: "If you use Bluetooth headphones, mice, keyboards, or other peripherals.".into(),
            how_to_undo: "Settings > Bluetooth & devices > Toggle Bluetooth on.".into(),
            tags: vec!["battery".into(), "bluetooth".into(), "wireless".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Microsoft\PolicyManager\default\Connectivity\AllowBluetooth".into(),
                name: "value".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "enable_usb_selective_suspend".into(),
            name: "Enable USB Selective Suspend".into(),
            description: "Allows Windows to suspend individual USB ports when devices are idle.".into(),
            why_it_helps: "USB devices draw power even when idle. Selective suspend powers down inactive USB ports individually, saving battery without disconnecting active devices.".into(),
            category: TweakCategory::Battery,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Moderate battery savings, especially with multiple USB devices".into(),
            when_not_to_use: "If you experience USB device disconnection issues or use time-sensitive USB devices.".into(),
            how_to_undo: "Settings > System > Power & battery > USB settings.".into(),
            tags: vec!["battery".into(), "usb".into(), "power".into()],
            actions: vec![TweakAction::PowerCfgSetting {
                subgroup_guid: "2a737441-1930-4402-8d77-b2bebba308a3".into(),
                setting_guid: "48e6b7a6-50f5-4782-a5d4-53bb8f07e226".into(),
                ac_value: None,
                dc_value: Some(1),
            }],
        },
        TweakDefinition {
            id: "reduce_processor_max_battery".into(),
            name: "Limit CPU to 80% on Battery".into(),
            description: "Caps maximum processor speed at 80% when running on battery power.".into(),
            why_it_helps: "The last 20% of CPU performance uses disproportionately more power. Capping at 80% provides most of the performance with significantly less power draw and heat.".into(),
            category: TweakCategory::Battery,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "20-40 minutes additional battery life, slightly lower peak performance".into(),
            when_not_to_use: "If you need full CPU performance on battery for demanding tasks.".into(),
            how_to_undo: "Set maximum processor state back to 100% in power plan settings.".into(),
            tags: vec!["battery".into(), "cpu".into(), "throttle".into()],
            actions: vec![TweakAction::PowerCfgSetting {
                subgroup_guid: "54533251-82be-4824-96c1-47b60b740d00".into(),
                setting_guid: "bc5038f7-23e0-4960-96da-33abaf5935ec".into(),
                ac_value: None,
                dc_value: Some(80),
            }],
        },
        TweakDefinition {
            id: "enable_hibernate".into(),
            name: "Enable Hibernate Mode".into(),
            description: "Enables hibernation so the laptop can save state to disk and fully power off.".into(),
            why_it_helps: "Hibernate saves your session to disk and completely powers off, using zero battery. Sleep still draws a small amount of power, which can drain the battery overnight or in a bag.".into(),
            category: TweakCategory::Battery,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Prevents battery drain during extended sleep, uses disk space equal to RAM".into(),
            when_not_to_use: "If you have limited SSD space (hibernate file = RAM size) or need instant wake.".into(),
            how_to_undo: "Run: powercfg /hibernate off".into(),
            tags: vec!["battery".into(), "hibernate".into(), "sleep".into()],
            actions: vec![TweakAction::Command {
                apply_cmd: "powercfg /hibernate on".into(),
                revert_cmd: "powercfg /hibernate off".into(),
            }],
        },
        TweakDefinition {
            id: "aggressive_battery_saver".into(),
            name: "Battery Saver at 30%".into(),
            description: "Activates Windows Battery Saver mode when battery drops to 30%.".into(),
            why_it_helps: "Battery Saver reduces background activity, push notifications, and display brightness. Activating it earlier at 30% gives more runway to find a charger.".into(),
            category: TweakCategory::Battery,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Extends usable battery life by triggering power saving earlier".into(),
            when_not_to_use: "If you find Battery Saver mode too restrictive for your workflow.".into(),
            how_to_undo: "Settings > System > Power & battery > Battery saver threshold.".into(),
            tags: vec!["battery".into(), "saver".into(), "threshold".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\EnergySaver\Parameters".into(),
                name: "BatteryThreshold".into(),
                desired_value: RegistryValueData::Dword(30),
            }],
        },
        TweakDefinition {
            id: "disable_background_on_battery".into(),
            name: "Restrict Background Apps on Battery".into(),
            description: "Prevents most background apps from running when on battery power.".into(),
            why_it_helps: "Background apps consume CPU cycles, network bandwidth, and memory even when you're not using them. Restricting them on battery significantly reduces power drain.".into(),
            category: TweakCategory::Battery,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: true,
            reversible: true,
            impact_estimate: "Noticeable battery improvement, some apps may not update in background".into(),
            when_not_to_use: "If you rely on background sync for email, messaging, or other apps.".into(),
            how_to_undo: "Settings > System > Power & battery > Battery usage per app.".into(),
            tags: vec!["battery".into(), "background".into(), "apps".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications".into(),
                name: "GlobalUserDisabled".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "reduce_display_brightness_battery".into(),
            name: "Enable Adaptive Brightness on Battery".into(),
            description: "Enables adaptive brightness to automatically lower display brightness based on ambient light.".into(),
            why_it_helps: "Adaptive brightness uses the ambient light sensor to dim the display in darker environments, saving significant power since the display is the biggest battery consumer.".into(),
            category: TweakCategory::Battery,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Significant battery savings in varying lighting conditions".into(),
            when_not_to_use: "If your laptop lacks an ambient light sensor or you need consistent brightness for color-sensitive work.".into(),
            how_to_undo: "Settings > System > Display > Brightness > Adaptive brightness.".into(),
            tags: vec!["battery".into(), "display".into(), "brightness".into()],
            actions: vec![TweakAction::PowerCfgSetting {
                subgroup_guid: "7516b95f-f776-4464-8c53-06167f40cc99".into(),
                setting_guid: "fbd9aa66-9553-4097-ba44-ed6e9d65eab8".into(),
                ac_value: None,
                dc_value: Some(1),
            }],
        },
    ]
}
