use crate::engine::tweak::*;

pub fn tweaks() -> Vec<TweakDefinition> {
    vec![
        TweakDefinition {
            id: "clean_temp_files".into(),
            name: "Clean Temporary Files".into(),
            description: "Deletes temporary files from Windows and user temp folders.".into(),
            why_it_helps: "Temporary files accumulate over time and can consume gigabytes of disk space. Cleaning them frees up storage and can slightly improve disk performance. These files are safe to delete — programs recreate them as needed.".into(),
            category: TweakCategory::Cleanup,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: false,
            impact_estimate: "Frees disk space (often 500MB-5GB)".into(),
            when_not_to_use: "If active programs are using temporary files (close all apps first).".into(),
            how_to_undo: "Deleted files cannot be recovered.".into(),
            tags: vec!["cleanup".into(), "disk".into(), "temp".into()],
            actions: vec![
                TweakAction::DeleteFiles {
                    paths: vec![
                        "%TEMP%".into(),
                        "%WINDIR%\\Temp".into(),
                    ],
                },
            ],
        },
        TweakDefinition {
            id: "clean_prefetch".into(),
            name: "Clean Prefetch Cache".into(),
            description: "Clears the Windows prefetch cache used for app launch optimization.".into(),
            why_it_helps: "The prefetch cache stores data about app launch patterns. Over time it can accumulate stale entries. Clearing it forces Windows to rebuild it with fresh data, which can marginally improve load times.".into(),
            category: TweakCategory::Cleanup,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Advanced,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: false,
            impact_estimate: "Frees some disk space, fresh prefetch data".into(),
            when_not_to_use: "If you want the fastest possible app launch times (prefetch helps with this).".into(),
            how_to_undo: "Windows will rebuild the prefetch cache automatically over time.".into(),
            tags: vec!["cleanup".into(), "disk".into(), "prefetch".into()],
            actions: vec![TweakAction::DeleteFiles {
                paths: vec!["%WINDIR%\\Prefetch".into()],
            }],
        },
        TweakDefinition {
            id: "clean_browser_cache".into(),
            name: "Clean Browser Caches".into(),
            description: "Deletes cached files from Chrome, Edge, and Firefox browsers.".into(),
            why_it_helps: "Browser caches can grow to several gigabytes over time. Clearing them frees disk space and can resolve stale content issues. Browsers will rebuild their caches automatically as you browse.".into(),
            category: TweakCategory::Cleanup,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: false,
            impact_estimate: "Frees disk space (often 500MB-3GB)".into(),
            when_not_to_use: "If browsers are currently open — close them first for a complete clean.".into(),
            how_to_undo: "Deleted cache files cannot be recovered. Browsers will rebuild caches.".into(),
            tags: vec!["cleanup".into(), "disk".into(), "browser".into(), "cache".into()],
            actions: vec![TweakAction::DeleteFiles {
                paths: vec![
                    "%LOCALAPPDATA%\\Google\\Chrome\\User Data\\Default\\Cache".into(),
                    "%LOCALAPPDATA%\\Google\\Chrome\\User Data\\Default\\Code Cache".into(),
                    "%LOCALAPPDATA%\\Microsoft\\Edge\\User Data\\Default\\Cache".into(),
                    "%LOCALAPPDATA%\\Microsoft\\Edge\\User Data\\Default\\Code Cache".into(),
                    "%LOCALAPPDATA%\\Mozilla\\Firefox\\Profiles".into(),
                ],
            }],
        },
        TweakDefinition {
            id: "clean_shader_cache".into(),
            name: "Clean GPU Shader Caches".into(),
            description: "Deletes compiled shader caches from NVIDIA and AMD GPUs.".into(),
            why_it_helps: "GPU drivers cache compiled shaders to speed up game loading. Over time these caches grow large and may contain stale entries from uninstalled games. Clearing them forces a fresh rebuild.".into(),
            category: TweakCategory::Cleanup,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: false,
            impact_estimate: "Frees disk space (100MB-2GB), fresh shader compilation".into(),
            when_not_to_use: "Right before a gaming session — first launch after clearing will have longer load times.".into(),
            how_to_undo: "Deleted shader caches cannot be recovered. Drivers will rebuild them.".into(),
            tags: vec!["cleanup".into(), "disk".into(), "gpu".into(), "shader".into(), "gaming".into()],
            actions: vec![TweakAction::DeleteFiles {
                paths: vec![
                    "%LOCALAPPDATA%\\NVIDIA\\DXCache".into(),
                    "%LOCALAPPDATA%\\NVIDIA\\GLCache".into(),
                    "%LOCALAPPDATA%\\AMD\\DxCache".into(),
                ],
            }],
        },
        TweakDefinition {
            id: "clean_delivery_optimization".into(),
            name: "Clean Delivery Optimization Cache".into(),
            description: "Deletes the Windows Delivery Optimization file cache.".into(),
            why_it_helps: "Delivery Optimization caches Windows Update files for peer-to-peer sharing with other PCs. This cache can grow to several gigabytes and is unnecessary once updates are installed.".into(),
            category: TweakCategory::Cleanup,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: false,
            impact_estimate: "Frees disk space (500MB-5GB)".into(),
            when_not_to_use: "If you use Delivery Optimization to update other PCs on your network.".into(),
            how_to_undo: "Deleted files cannot be recovered. Cache will rebuild with future updates.".into(),
            tags: vec!["cleanup".into(), "disk".into(), "updates".into()],
            actions: vec![TweakAction::DeleteFiles {
                paths: vec![
                    "%WINDIR%\\SoftwareDistribution\\DeliveryOptimization".into(),
                ],
            }],
        },
        TweakDefinition {
            id: "clean_windows_update_cache".into(),
            name: "Clean Windows Update Cache".into(),
            description: "Deletes downloaded Windows Update files.".into(),
            why_it_helps: "Windows keeps downloaded update packages even after installation. Clearing this folder frees significant disk space and can resolve stuck update issues.".into(),
            category: TweakCategory::Cleanup,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: false,
            impact_estimate: "Frees disk space (500MB-10GB)".into(),
            when_not_to_use: "If Windows Update is currently installing updates.".into(),
            how_to_undo: "Deleted files cannot be recovered. Windows will re-download updates as needed.".into(),
            tags: vec!["cleanup".into(), "disk".into(), "updates".into()],
            actions: vec![TweakAction::DeleteFiles {
                paths: vec![
                    "%WINDIR%\\SoftwareDistribution\\Download".into(),
                ],
            }],
        },
        TweakDefinition {
            id: "clean_crash_dumps".into(),
            name: "Clean Crash Dumps".into(),
            description: "Deletes crash dump files from user and system directories.".into(),
            why_it_helps: "When applications or Windows crash, dump files are saved for debugging. These files can be large (hundreds of MB each) and accumulate over time. Most users never analyze them.".into(),
            category: TweakCategory::Cleanup,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: false,
            impact_estimate: "Frees disk space (100MB-2GB)".into(),
            when_not_to_use: "If you need crash dumps for debugging a recurring issue.".into(),
            how_to_undo: "Deleted dump files cannot be recovered.".into(),
            tags: vec!["cleanup".into(), "disk".into(), "crash".into(), "dumps".into()],
            actions: vec![TweakAction::DeleteFiles {
                paths: vec![
                    "%LOCALAPPDATA%\\CrashDumps".into(),
                    "%WINDIR%\\Minidump".into(),
                ],
            }],
        },
        TweakDefinition {
            id: "clean_log_files".into(),
            name: "Clean Log Files".into(),
            description: "Deletes Windows log files.".into(),
            why_it_helps: "Windows generates log files for system events, updates, and diagnostics. These accumulate over time and consume disk space without providing value to most users.".into(),
            category: TweakCategory::Cleanup,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: false,
            impact_estimate: "Frees disk space (100MB-1GB)".into(),
            when_not_to_use: "If you need log files for troubleshooting a system issue.".into(),
            how_to_undo: "Deleted log files cannot be recovered. New logs will be created.".into(),
            tags: vec!["cleanup".into(), "disk".into(), "logs".into()],
            actions: vec![TweakAction::DeleteFiles {
                paths: vec![
                    "%WINDIR%\\Logs".into(),
                ],
            }],
        },
        TweakDefinition {
            id: "clean_recycle_bin".into(),
            name: "Empty Recycle Bin".into(),
            description: "Permanently deletes all files in the Recycle Bin.".into(),
            why_it_helps: "The Recycle Bin holds deleted files, consuming disk space until emptied. This can accumulate to many gigabytes if you regularly delete large files or folders.".into(),
            category: TweakCategory::Cleanup,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: false,
            impact_estimate: "Frees disk space (varies widely)".into(),
            when_not_to_use: "If you might need to recover recently deleted files.".into(),
            how_to_undo: "Emptied Recycle Bin files cannot be recovered.".into(),
            tags: vec!["cleanup".into(), "disk".into(), "recycle".into()],
            actions: vec![TweakAction::Command {
                apply_cmd: "rd /s /q C:\\$Recycle.Bin".into(),
                revert_cmd: "echo done".into(),
            }],
        },
        TweakDefinition {
            id: "clean_font_cache".into(),
            name: "Clean Font Cache".into(),
            description: "Clears the Windows font cache and restarts the font service.".into(),
            why_it_helps: "A corrupted font cache can cause slow application launches, missing fonts, or display issues. Clearing it forces Windows to rebuild a fresh cache, resolving these problems.".into(),
            category: TweakCategory::Cleanup,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Advanced,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Fixes font rendering issues, small disk space savings".into(),
            when_not_to_use: "Unless you're experiencing font-related issues — the cache is normally helpful.".into(),
            how_to_undo: "Run: net start FontCache".into(),
            tags: vec!["cleanup".into(), "disk".into(), "fonts".into()],
            actions: vec![TweakAction::Command {
                apply_cmd: "net stop FontCache & del /f /s /q %WINDIR%\\ServiceProfiles\\LocalService\\AppData\\Local\\FontCache\\*".into(),
                revert_cmd: "net start FontCache".into(),
            }],
        },
    ]
}
