use crate::engine::tweak::*;

pub fn tweaks() -> Vec<TweakDefinition> {
    vec![
        TweakDefinition {
            id: "disable_game_bar".into(),
            name: "Disable Game Bar".into(),
            description: "Turns off the Xbox Game Bar overlay that can appear during games.".into(),
            why_it_helps: "The Game Bar overlay consumes GPU and CPU resources. Disabling it removes an unnecessary background process and prevents accidental overlay popups during gameplay.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Reduces background GPU usage, prevents overlay interruptions".into(),
            when_not_to_use: "If you use Xbox Game Bar for screenshots or recording.".into(),
            how_to_undo: "Re-enable in Windows Settings > Gaming > Game Bar.".into(),
            tags: vec!["gaming".into(), "fps".into(), "overlay".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\GameDVR".into(),
                    name: "AppCaptureEnabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\GameBar".into(),
                    name: "UseNexusForGameBarEnabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\GameBar".into(),
                    name: "AutoGameModeEnabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
        TweakDefinition {
            id: "disable_game_dvr".into(),
            name: "Disable Game DVR / Background Recording".into(),
            description: "Stops Windows from recording gameplay in the background.".into(),
            why_it_helps: "Background recording continuously encodes video, consuming significant GPU and CPU resources even when you're not actively recording. Disabling it frees those resources for your game.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Noticeable FPS improvement, especially on mid-range GPUs".into(),
            when_not_to_use: "If you use 'Record that' or background recording features.".into(),
            how_to_undo: "Re-enable in Windows Settings > Gaming > Captures.".into(),
            tags: vec!["gaming".into(), "fps".into(), "recording".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKLM,
                    path: r"SOFTWARE\Policies\Microsoft\Windows\GameDVR".into(),
                    name: "AllowGameDVR".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"System\GameConfigStore".into(),
                    name: "GameDVR_Enabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
        TweakDefinition {
            id: "enable_hags".into(),
            name: "Enable Hardware-Accelerated GPU Scheduling".into(),
            description: "Lets your GPU manage its own video memory scheduling instead of Windows.".into(),
            why_it_helps: "Reduces CPU overhead for GPU memory management, which can lower input latency and improve frame pacing in GPU-bound scenarios. Works best on NVIDIA 10-series+ and AMD 5000-series+.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Slight latency reduction, better frame pacing on supported GPUs".into(),
            when_not_to_use: "If you experience crashes or visual glitches with older GPU drivers.".into(),
            how_to_undo: "Disable in Windows Settings > Display > Graphics > Default Graphics Settings.".into(),
            tags: vec!["gaming".into(), "gpu".into(), "latency".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers".into(),
                name: "HwSchMode".into(),
                desired_value: RegistryValueData::Dword(2),
            }],
        },
        TweakDefinition {
            id: "disable_fullscreen_optimizations".into(),
            name: "Disable Fullscreen Optimizations".into(),
            description: "Prevents Windows from applying its borderless-fullscreen mode to games.".into(),
            why_it_helps: "Windows' fullscreen optimizations can add input lag and inconsistent frame timing. Disabling this system-wide lets games use true exclusive fullscreen for better performance.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Reduced input lag in fullscreen games".into(),
            when_not_to_use: "If you use alt-tab frequently and need fast switching in borderless mode.".into(),
            how_to_undo: "Delete the GameDVR_FSEBehavior registry value.".into(),
            tags: vec!["gaming".into(), "fps".into(), "fullscreen".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"System\GameConfigStore".into(),
                name: "GameDVR_FSEBehavior".into(),
                desired_value: RegistryValueData::Dword(2),
            }],
        },
        TweakDefinition {
            id: "disable_mouse_acceleration".into(),
            name: "Disable Mouse Acceleration".into(),
            description: "Turns off 'Enhance pointer precision' for 1:1 mouse movement.".into(),
            why_it_helps: "Mouse acceleration makes cursor speed depend on how fast you move the mouse, making aim inconsistent. Disabling it gives you predictable, linear mouse movement — essential for FPS games.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Consistent mouse movement, better aim in FPS games".into(),
            when_not_to_use: "If you prefer accelerated mouse movement for desktop productivity.".into(),
            how_to_undo: "Re-enable 'Enhance pointer precision' in Mouse settings.".into(),
            tags: vec!["gaming".into(), "mouse".into(), "aim".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"Control Panel\Mouse".into(),
                    name: "MouseSpeed".into(),
                    desired_value: RegistryValueData::String("0".into()),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"Control Panel\Mouse".into(),
                    name: "MouseThreshold1".into(),
                    desired_value: RegistryValueData::String("0".into()),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"Control Panel\Mouse".into(),
                    name: "MouseThreshold2".into(),
                    desired_value: RegistryValueData::String("0".into()),
                },
            ],
        },
        TweakDefinition {
            id: "disable_nagle".into(),
            name: "Disable Nagle's Algorithm".into(),
            description: "Disables TCP packet batching for lower network latency.".into(),
            why_it_helps: "Nagle's algorithm batches small TCP packets to reduce overhead, but this adds latency. Disabling it sends packets immediately, which can reduce ping in online games by a few milliseconds.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "1-5ms ping reduction in online games".into(),
            when_not_to_use: "If you need maximum network throughput over minimal latency.".into(),
            how_to_undo: "Remove the TCPNoDelay registry value.".into(),
            tags: vec!["gaming".into(), "network".into(), "latency".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Microsoft\MSMQ\Parameters".into(),
                name: "TCPNoDelay".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "gpu_high_performance".into(),
            name: "Set GPU to High Performance Preference".into(),
            description: "Tells Windows to prefer the high-performance GPU for all applications.".into(),
            why_it_helps: "On systems with integrated + discrete GPUs, Windows may default to the power-saving integrated GPU. This ensures your dedicated GPU is used for everything.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Ensures games use your dedicated GPU".into(),
            when_not_to_use: "If you want Windows to manage GPU selection to save power on laptops.".into(),
            how_to_undo: "Reset GPU preferences in Windows Settings > Display > Graphics.".into(),
            tags: vec!["gaming".into(), "gpu".into(), "performance".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\DirectX\UserGpuPreferences".into(),
                name: "DirectXUserGlobalSettings".into(),
                desired_value: RegistryValueData::String("VRROptimizeEnable=1;SwapEffectUpgradeEnable=1;".into()),
            }],
        },
        TweakDefinition {
            id: "disable_game_mode".into(),
            name: "Disable Windows Game Mode".into(),
            description: "Turns off Windows Game Mode which can sometimes cause stuttering.".into(),
            why_it_helps: "While Game Mode is meant to help, it can cause micro-stuttering and inconsistent frame times in some games. If you're experiencing stutters, disabling it may help.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "May reduce stuttering in some games".into(),
            when_not_to_use: "If Game Mode actually helps your specific games (test both ways).".into(),
            how_to_undo: "Re-enable in Windows Settings > Gaming > Game Mode.".into(),
            tags: vec!["gaming".into(), "fps".into(), "stutter".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\GameBar".into(),
                name: "AllowAutoGameMode".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_xbox_services".into(),
            name: "Disable Xbox Background Services".into(),
            description: "Sets Xbox authentication and game-save services to manual start.".into(),
            why_it_helps: "Xbox services (XblAuthManager, XblGameSave) run in the background even if you don't use Xbox features. Setting them to manual frees up RAM and CPU cycles for games.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Frees background resources used by Xbox services".into(),
            when_not_to_use: "If you use Xbox Live achievements, cloud saves, or Game Pass on PC.".into(),
            how_to_undo: "Set XblAuthManager and XblGameSave services back to Automatic in services.msc.".into(),
            tags: vec!["gaming".into(), "xbox".into(), "services".into(), "ram".into()],
            actions: vec![
                TweakAction::Service {
                    name: "XblAuthManager".into(),
                    desired_startup: ServiceStartup::Manual,
                },
                TweakAction::Service {
                    name: "XblGameSave".into(),
                    desired_startup: ServiceStartup::Manual,
                },
            ],
        },
        TweakDefinition {
            id: "disable_notification_popups_gaming".into(),
            name: "Suppress Notification Popups".into(),
            description: "Disables toast notification popups system-wide.".into(),
            why_it_helps: "Toast notifications can overlay on top of fullscreen games, causing framerate dips and distracting you at critical moments. Disabling them ensures uninterrupted gameplay.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No popup interruptions during gameplay".into(),
            when_not_to_use: "If you need real-time toast notifications for messaging or alerts.".into(),
            how_to_undo: "Set ToastEnabled back to 1 in the registry or re-enable in notification settings.".into(),
            tags: vec!["gaming".into(), "notifications".into(), "fps".into(), "focus".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\PushNotifications".into(),
                name: "ToastEnabled".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "enable_focus_assist_gaming".into(),
            name: "Enable Focus Assist for Gaming".into(),
            description: "Suppresses notifications and lock-screen toasts for distraction-free gaming.".into(),
            why_it_helps: "Focus Assist suppresses all non-critical notifications, preventing popups, sounds, and badge updates from interrupting your gaming sessions or focused work.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Eliminates notification distractions during gaming".into(),
            when_not_to_use: "If you need to receive all notifications in real-time.".into(),
            how_to_undo: "Disable Focus Assist in Settings > System > Focus or re-enable notification values.".into(),
            tags: vec!["gaming".into(), "focus".into(), "notifications".into(), "dnd".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings".into(),
                    name: "NOC_GLOBAL_SETTING_ALLOW_TOASTS_ABOVE_LOCK".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings".into(),
                    name: "NOC_GLOBAL_SETTING_ALLOW_CRITICAL_TOASTS_ABOVE_LOCK".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
        TweakDefinition {
            id: "disable_power_throttling".into(),
            name: "Disable Power Throttling".into(),
            description: "Prevents Windows from throttling CPU performance to save power.".into(),
            why_it_helps: "Power throttling reduces CPU clock speeds for background processes to save energy. Disabling it ensures all processes, including game-related background tasks, run at full speed.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Consistent CPU performance, prevents background task slowdowns".into(),
            when_not_to_use: "On laptops where battery life is important, or if thermal throttling is a concern.".into(),
            how_to_undo: "Delete the PowerThrottlingOff value from HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\\PowerThrottling.".into(),
            tags: vec!["gaming".into(), "cpu".into(), "performance".into(), "power".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SYSTEM\CurrentControlSet\Control\Power\PowerThrottling".into(),
                name: "PowerThrottlingOff".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "boost_game_priority".into(),
            name: "Boost Foreground Game Priority".into(),
            description: "Configures processor scheduling to strongly favor foreground applications.".into(),
            why_it_helps: "Win32PrioritySeparation controls how much CPU time foreground apps get versus background tasks. Setting it to 0x26 gives short, variable, high-priority quantum to the foreground game, reducing stutter from background processes.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Smoother frame times when background tasks are running".into(),
            when_not_to_use: "If you run important background tasks that need consistent CPU time (e.g., streaming while gaming).".into(),
            how_to_undo: "Set Win32PrioritySeparation back to default value 2 (0x02) in the registry.".into(),
            tags: vec!["gaming".into(), "cpu".into(), "fps".into(), "stutter".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SYSTEM\CurrentControlSet\Control\PriorityControl".into(),
                name: "Win32PrioritySeparation".into(),
                desired_value: RegistryValueData::Dword(0x26),
            }],
        },
        TweakDefinition {
            id: "disable_core_parking".into(),
            name: "Disable CPU Core Parking".into(),
            description: "Prevents Windows from parking CPU cores to save power.".into(),
            why_it_helps: "Core parking puts idle CPU cores to sleep. Waking them introduces latency spikes that cause micro-stutter in games. Keeping all cores active ensures instant responsiveness.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Reduces micro-stutter from core wake-up latency".into(),
            when_not_to_use: "On laptops or if you want to reduce power consumption and heat output.".into(),
            how_to_undo: "Run: powercfg -setacvalueindex SCHEME_CURRENT SUB_PROCESSOR CPMINCORES 5".into(),
            tags: vec!["gaming".into(), "cpu".into(), "latency".into(), "stutter".into()],
            actions: vec![TweakAction::PowerCfgSetting {
                subgroup_guid: "54533251-82be-4824-96c1-47b60b740d00".into(),
                setting_guid: "0cc5b647-c1df-4637-891a-dec35c318583".into(),
                ac_value: Some(100),
                dc_value: None,
            }],
        },
        TweakDefinition {
            id: "disable_dynamic_tick".into(),
            name: "Disable Dynamic Tick".into(),
            description: "Forces a fixed system timer tick rate instead of a dynamic one.".into(),
            why_it_helps: "The dynamic tick adjusts the system timer frequency based on load, which can cause inconsistent frame pacing in timing-sensitive games. A fixed tick provides a stable timing baseline.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Advanced,
            recommendation: Recommendation::Advanced,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "More consistent frame pacing in timing-sensitive games".into(),
            when_not_to_use: "On laptops or systems where idle power draw matters. May increase power consumption at idle.".into(),
            how_to_undo: "Run: bcdedit /deletevalue disabledynamictick".into(),
            tags: vec!["gaming".into(), "latency".into(), "stutter".into(), "advanced".into()],
            actions: vec![TweakAction::Command {
                apply_cmd: "bcdedit /set disabledynamictick yes".into(),
                revert_cmd: "bcdedit /deletevalue disabledynamictick".into(),
            }],
        },
        TweakDefinition {
            id: "optimize_gpu_scheduling".into(),
            name: "Disable GPU Preemption".into(),
            description: "Disables GPU compute preemption for uninterrupted rendering.".into(),
            why_it_helps: "GPU preemption allows Windows to interrupt GPU work for scheduling purposes. Disabling it lets the GPU finish rendering frames without interruption, potentially improving frame consistency in demanding games.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Advanced,
            recommendation: Recommendation::Advanced,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "May improve frame consistency in GPU-heavy games".into(),
            when_not_to_use: "If you use GPU-accelerated apps alongside games (video editing, streaming). May cause desktop responsiveness issues.".into(),
            how_to_undo: "Delete EnablePreemption from HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers.".into(),
            tags: vec!["gaming".into(), "gpu".into(), "fps".into(), "advanced".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SYSTEM\CurrentControlSet\Control\GraphicsDrivers".into(),
                name: "EnablePreemption".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_game_bar_presence_writer".into(),
            name: "Disable Game Bar Presence Writer".into(),
            description: "Disables the Game Bar background process that tracks running games.".into(),
            why_it_helps: "The Game Bar Presence Writer continuously monitors which games are running, using CPU cycles and causing micro-stutters. Disabling it removes this unnecessary background monitoring.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Eliminates Game Bar background monitoring overhead".into(),
            when_not_to_use: "If you rely on Game Bar's automatic game detection features.".into(),
            how_to_undo: "Set ActivationType back to 1 in the registry.".into(),
            tags: vec!["gaming".into(), "fps".into(), "stutter".into(), "background".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Microsoft\WindowsRuntime\ActivatableClassId\Windows.Gaming.GameBar.PresenceServer.Internal.PresenceWriter".into(),
                name: "ActivationType".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_windows_error_reporting".into(),
            name: "Disable Windows Error Reporting".into(),
            description: "Disables the Windows Error Reporting service that collects crash data.".into(),
            why_it_helps: "WER monitors all applications for crashes and hangs, consuming resources to collect and upload diagnostic data. Disabling it prevents background overhead and avoids popup dialogs when games crash.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Removes crash reporting overhead, no error dialog popups".into(),
            when_not_to_use: "If you want crash reports sent to Microsoft for diagnosis, or use corporate error reporting.".into(),
            how_to_undo: "Set the WerSvc service back to Manual in services.msc.".into(),
            tags: vec!["gaming".into(), "services".into(), "background".into()],
            actions: vec![TweakAction::Service {
                name: "WerSvc".into(),
                desired_startup: ServiceStartup::Disabled,
            }],
        },
        TweakDefinition {
            id: "optimize_timer_resolution".into(),
            name: "Optimize System Timer Resolution".into(),
            description: "Enables global high-resolution timer requests for tighter timing precision.".into(),
            why_it_helps: "Windows defaults to a ~15.6ms timer resolution. Enabling global timer resolution requests allows applications to use a higher resolution timer (~0.5ms), which improves frame pacing and reduces input lag.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Tighter frame pacing and reduced input latency".into(),
            when_not_to_use: "On laptops where the increased timer frequency may impact battery life.".into(),
            how_to_undo: "Delete GlobalTimerResolutionRequests from the kernel registry key.".into(),
            tags: vec!["gaming".into(), "latency".into(), "fps".into(), "timer".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SYSTEM\CurrentControlSet\Control\Session Manager\kernel".into(),
                name: "GlobalTimerResolutionRequests".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "disable_spectre_mitigations".into(),
            name: "Disable Spectre/Meltdown Mitigations".into(),
            description: "Disables CPU vulnerability mitigations for maximum performance.".into(),
            why_it_helps: "Spectre and Meltdown mitigations add overhead to every system call and context switch. Disabling them can recover 5-15% CPU performance depending on workload, but leaves the system vulnerable to these exploits.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Advanced,
            recommendation: Recommendation::Advanced,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "5-15% CPU performance improvement at the cost of security".into(),
            when_not_to_use: "On systems exposed to untrusted code, shared environments, or if security is a priority. NOT recommended for daily-driver PCs.".into(),
            how_to_undo: "Delete FeatureSettingsOverride and FeatureSettingsOverrideMask from the Memory Management registry key.".into(),
            tags: vec!["gaming".into(), "cpu".into(), "performance".into(), "advanced".into(), "security".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKLM,
                    path: r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management".into(),
                    name: "FeatureSettingsOverride".into(),
                    desired_value: RegistryValueData::Dword(3),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKLM,
                    path: r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management".into(),
                    name: "FeatureSettingsOverrideMask".into(),
                    desired_value: RegistryValueData::Dword(3),
                },
            ],
        },
        TweakDefinition {
            id: "enable_msi_mode".into(),
            name: "Enable MSI Mode for GPU".into(),
            description: "Enables Message Signaled Interrupts for the graphics card.".into(),
            why_it_helps: "MSI mode allows the GPU to signal interrupts directly to the CPU without routing through the legacy interrupt controller. This reduces interrupt latency and can eliminate DPC latency spikes that cause micro-stutter.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Advanced,
            recommendation: Recommendation::Advanced,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Reduced DPC latency, fewer micro-stutters from interrupt handling".into(),
            when_not_to_use: "If your GPU already has MSI enabled (most modern GPUs do), or if you experience instability after applying.".into(),
            how_to_undo: "Revert MSISupported to 0 using the same PowerShell command.".into(),
            tags: vec!["gaming".into(), "gpu".into(), "latency".into(), "advanced".into()],
            actions: vec![TweakAction::Command {
                apply_cmd: r#"powershell -Command "foreach ($dev in (Get-PnpDevice -Class Display -Status OK)) { $regPath = 'HKLM:\SYSTEM\CurrentControlSet\Enum\' + $dev.InstanceId + '\Device Parameters\Interrupt Management\MessageSignaledInterruptProperties'; if (!(Test-Path $regPath)) { New-Item -Path $regPath -Force | Out-Null }; Set-ItemProperty -Path $regPath -Name MSISupported -Value 1 -Type DWord }""#.into(),
                revert_cmd: r#"powershell -Command "foreach ($dev in (Get-PnpDevice -Class Display -Status OK)) { $regPath = 'HKLM:\SYSTEM\CurrentControlSet\Enum\' + $dev.InstanceId + '\Device Parameters\Interrupt Management\MessageSignaledInterruptProperties'; if (Test-Path $regPath) { Set-ItemProperty -Path $regPath -Name MSISupported -Value 0 -Type DWord } }""#.into(),
            }],
        },
        TweakDefinition {
            id: "disable_prefetch_for_ssd".into(),
            name: "Disable Prefetch for SSD".into(),
            description: "Disables the Windows prefetcher on SSD-equipped systems.".into(),
            why_it_helps: "The prefetcher was designed for HDDs to preload frequently-used data. On SSDs, it adds unnecessary write overhead without meaningful read speed improvements. Disabling it reduces background disk activity.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Reduced background disk writes on SSD systems".into(),
            when_not_to_use: "If your system uses an HDD as the primary drive — prefetch significantly helps HDD performance.".into(),
            how_to_undo: "Set EnablePrefetcher back to 3 (default) in the registry.".into(),
            tags: vec!["gaming".into(), "ssd".into(), "disk".into(), "performance".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters".into(),
                name: "EnablePrefetcher".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_superfetch_for_ssd".into(),
            name: "Disable Superfetch (SysMain) for SSD".into(),
            description: "Disables the SysMain service that preloads apps into memory.".into(),
            why_it_helps: "SysMain (formerly Superfetch) preloads frequently-used applications into RAM. On SSD systems with fast random reads, this provides negligible benefit while consuming RAM and causing background disk activity that can interfere with game loading.".into(),
            category: TweakCategory::Gaming,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Reduced RAM usage and background disk I/O on SSD systems".into(),
            when_not_to_use: "If you have an HDD or limited RAM — SysMain helps keep frequently-used apps responsive.".into(),
            how_to_undo: "Set the SysMain service back to Automatic in services.msc.".into(),
            tags: vec!["gaming".into(), "ssd".into(), "ram".into(), "performance".into()],
            actions: vec![TweakAction::Service {
                name: "SysMain".into(),
                desired_startup: ServiceStartup::Disabled,
            }],
        },
    ]
}
