use crate::engine::tweak::*;

pub fn tweaks() -> Vec<TweakDefinition> {
    vec![
        TweakDefinition {
            id: "disable_auto_tuning".into(),
            name: "Disable TCP Auto-Tuning".into(),
            description: "Disables the Windows TCP receive window auto-tuning feature.".into(),
            why_it_helps: "TCP auto-tuning can cause issues with some routers and firewalls, leading to slow downloads or connection drops. Disabling it provides more predictable network behavior.".into(),
            category: TweakCategory::Network,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "May fix slow transfers on incompatible networks".into(),
            when_not_to_use: "If your network works fine — auto-tuning generally improves throughput on modern networks.".into(),
            how_to_undo: "Run: netsh int tcp set global autotuninglevel=normal".into(),
            tags: vec!["network".into(), "tcp".into(), "throughput".into()],
            actions: vec![TweakAction::Command {
                apply_cmd: "netsh int tcp set global autotuninglevel=disabled".into(),
                revert_cmd: "netsh int tcp set global autotuninglevel=normal".into(),
            }],
        },
        TweakDefinition {
            id: "disable_qos_bandwidth".into(),
            name: "Disable QoS Reserved Bandwidth".into(),
            description: "Removes the bandwidth reservation that Windows QoS Packet Scheduler holds.".into(),
            why_it_helps: "Windows reserves up to 20% of bandwidth for QoS by default. Setting it to 0 ensures all bandwidth is available to applications.".into(),
            category: TweakCategory::Network,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Reclaims up to 20% reserved bandwidth".into(),
            when_not_to_use: "If you use QoS policies for VoIP or enterprise traffic shaping.".into(),
            how_to_undo: "Delete NonBestEffortLimit from HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Psched.".into(),
            tags: vec!["network".into(), "bandwidth".into(), "throughput".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Policies\Microsoft\Windows\Psched".into(),
                name: "NonBestEffortLimit".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_p2p_updates".into(),
            name: "Disable P2P Update Delivery".into(),
            description: "Prevents Windows Update from sharing downloaded updates with other PCs over the internet.".into(),
            why_it_helps: "Stops Windows from using your upload bandwidth to distribute updates to other computers, keeping your bandwidth for your own use.".into(),
            category: TweakCategory::Network,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Saves upload bandwidth, especially on slow connections".into(),
            when_not_to_use: "On local networks where you want fast update distribution between PCs.".into(),
            how_to_undo: "Settings > Windows Update > Advanced options > Delivery Optimization.".into(),
            tags: vec!["network".into(), "bandwidth".into(), "updates".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization".into(),
                name: "DODownloadMode".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_network_throttling".into(),
            name: "Disable Network Throttling".into(),
            description: "Removes the default network throttling that Windows applies to multimedia streams.".into(),
            why_it_helps: "Windows throttles non-multimedia network traffic to 10 packets per millisecond by default. Disabling this allows full network throughput for all applications.".into(),
            category: TweakCategory::Network,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Removes default 10 Mbps throttle on non-multimedia traffic".into(),
            when_not_to_use: "If you need to prioritize multimedia streaming over other traffic.".into(),
            how_to_undo: "Delete NetworkThrottlingIndex or set it to 10 (default).".into(),
            tags: vec!["network".into(), "throughput".into(), "latency".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile".into(),
                name: "NetworkThrottlingIndex".into(),
                desired_value: RegistryValueData::Dword(0xFFFFFFFF),
            }],
        },
        TweakDefinition {
            id: "disable_nagle_algorithm".into(),
            name: "Disable Nagle's Algorithm (Global)".into(),
            description: "Disables TCP packet batching globally for lower latency.".into(),
            why_it_helps: "Nagle's algorithm combines small outgoing TCP packets to reduce overhead, but adds latency. Disabling it sends packets immediately, reducing round-trip times for interactive applications.".into(),
            category: TweakCategory::Network,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "1-5ms latency reduction for interactive traffic".into(),
            when_not_to_use: "If you prioritize throughput over latency, or on metered connections.".into(),
            how_to_undo: "Delete or set TCPNoDelay to 0 in HKLM\\SOFTWARE\\Microsoft\\MSMQ\\Parameters.".into(),
            tags: vec!["network".into(), "latency".into(), "gaming".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Microsoft\MSMQ\Parameters".into(),
                name: "TCPNoDelay".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "optimize_network_adapter_power".into(),
            name: "Prevent Network Adapter Sleep".into(),
            description: "Disables power management on all network adapters to prevent disconnects.".into(),
            why_it_helps: "Windows can put network adapters to sleep to save power, causing brief disconnections and increased latency when waking. This keeps adapters always active.".into(),
            category: TweakCategory::Network,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Prevents intermittent network drops, slightly higher power usage".into(),
            when_not_to_use: "On laptops where battery life is more important than constant connectivity.".into(),
            how_to_undo: "Run: powershell \"Get-NetAdapter -Physical | Enable-NetAdapterPowerManagement\"".into(),
            tags: vec!["network".into(), "power".into(), "stability".into()],
            actions: vec![TweakAction::Command {
                apply_cmd: "powershell -Command \"Get-NetAdapter -Physical | Disable-NetAdapterPowerManagement -ErrorAction SilentlyContinue\"".into(),
                revert_cmd: "powershell -Command \"Get-NetAdapter -Physical | Enable-NetAdapterPowerManagement -ErrorAction SilentlyContinue\"".into(),
            }],
        },
        TweakDefinition {
            id: "enable_dns_cache_optimization".into(),
            name: "Optimize DNS Cache".into(),
            description: "Increases the DNS cache TTL and reduces negative cache duration.".into(),
            why_it_helps: "Longer positive cache (24h) means fewer repeated DNS lookups for frequently visited sites. Shorter negative cache (5s) means failed lookups are retried faster.".into(),
            category: TweakCategory::Network,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Faster page loads for repeated visits, quicker recovery from DNS failures".into(),
            when_not_to_use: "If you frequently switch DNS servers or need immediate DNS propagation.".into(),
            how_to_undo: "Delete MaxCacheTtl and MaxNegativeCacheTtl from the Dnscache\\Parameters key.".into(),
            tags: vec!["network".into(), "dns".into(), "latency".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKLM,
                    path: r"SYSTEM\CurrentControlSet\Services\Dnscache\Parameters".into(),
                    name: "MaxCacheTtl".into(),
                    desired_value: RegistryValueData::Dword(86400),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKLM,
                    path: r"SYSTEM\CurrentControlSet\Services\Dnscache\Parameters".into(),
                    name: "MaxNegativeCacheTtl".into(),
                    desired_value: RegistryValueData::Dword(5),
                },
            ],
        },
        TweakDefinition {
            id: "disable_wifi_sense_network".into(),
            name: "Disable Wi-Fi Sense Auto-Connect".into(),
            description: "Prevents Windows from automatically connecting to suggested Wi-Fi hotspots.".into(),
            why_it_helps: "Stops Windows from connecting to open or shared Wi-Fi networks without your explicit consent, improving security and preventing unexpected network switches.".into(),
            category: TweakCategory::Network,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No performance impact, improved network security".into(),
            when_not_to_use: "If you travel frequently and rely on automatic hotspot connections.".into(),
            how_to_undo: "Delete or set AllowAutoConnectToWiFiSenseHotspots to 1.".into(),
            tags: vec!["network".into(), "wifi".into(), "security".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Microsoft\PolicyManager\default\WiFi\AllowAutoConnectToWiFiSenseHotspots".into(),
                name: "value".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_ipv6".into(),
            name: "Disable IPv6".into(),
            description: "Disables the IPv6 protocol stack on all network adapters.".into(),
            why_it_helps: "On networks without proper IPv6 infrastructure, the protocol can cause DNS delays and connection timeouts as Windows tries IPv6 first before falling back to IPv4.".into(),
            category: TweakCategory::Network,
            risk_level: RiskLevel::Advanced,
            recommendation: Recommendation::Advanced,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Eliminates IPv6 fallback delays on IPv4-only networks".into(),
            when_not_to_use: "If your ISP or network provides native IPv6 connectivity. Some apps and services require IPv6.".into(),
            how_to_undo: "Delete DisabledComponents or set to 0 in Tcpip6\\Parameters.".into(),
            tags: vec!["network".into(), "ipv6".into(), "advanced".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters".into(),
                name: "DisabledComponents".into(),
                desired_value: RegistryValueData::Dword(0xFF),
            }],
        },
        TweakDefinition {
            id: "optimize_tcp_timestamps".into(),
            name: "Disable TCP Timestamps".into(),
            description: "Disables TCP timestamp options in packet headers.".into(),
            why_it_helps: "Removes 12 bytes of overhead from every TCP packet header, providing a minor latency improvement and reducing network fingerprinting surface.".into(),
            category: TweakCategory::Network,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Minor latency reduction, slightly less overhead per packet".into(),
            when_not_to_use: "On high-latency or lossy networks where TCP timestamps help with accurate RTT measurement.".into(),
            how_to_undo: "Run: netsh int tcp set global timestamps=enabled".into(),
            tags: vec!["network".into(), "tcp".into(), "latency".into()],
            actions: vec![TweakAction::Command {
                apply_cmd: "netsh int tcp set global timestamps=disabled".into(),
                revert_cmd: "netsh int tcp set global timestamps=enabled".into(),
            }],
        },
    ]
}
