use crate::engine::tweak::*;

pub fn tweaks() -> Vec<TweakDefinition> {
    vec![
        TweakDefinition {
            id: "disable_background_apps".into(),
            name: "Disable Background Apps".into(),
            description: "Prevents UWP/Store apps from running in the background.".into(),
            why_it_helps: "Windows Store apps can run background tasks even when not open, consuming CPU, RAM, and network. Disabling this stops them from waking up unless you actively use them.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Reduced idle CPU and RAM usage".into(),
            when_not_to_use: "If you rely on Store apps running in the background (e.g., Mail, Calendar).".into(),
            how_to_undo: "Re-enable in Windows Settings > Apps > Installed apps > app permissions.".into(),
            tags: vec!["performance".into(), "ram".into(), "cpu".into(), "uwp".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications".into(),
                name: "GlobalUserDisabled".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "disable_sysmain".into(),
            name: "Disable SysMain (Superfetch)".into(),
            description: "Disables the SysMain service that preloads frequently used apps.".into(),
            why_it_helps: "SysMain preloads apps into RAM, which causes high disk usage on HDDs and is unnecessary on SSDs. If you have an SSD, disabling it reduces background disk activity without affecting performance.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Reduced disk usage on SSDs, less background activity".into(),
            when_not_to_use: "If you have an HDD and frequently reopen the same apps.".into(),
            how_to_undo: "Re-enable SysMain service in Services (services.msc).".into(),
            tags: vec!["performance".into(), "disk".into(), "ssd".into(), "service".into()],
            actions: vec![TweakAction::Service {
                name: "SysMain".into(),
                desired_startup: ServiceStartup::Disabled,
            }],
        },
        TweakDefinition {
            id: "disable_search_indexing".into(),
            name: "Disable Windows Search Indexing".into(),
            description: "Stops Windows from indexing files in the background for search.".into(),
            why_it_helps: "The Windows Search indexer runs continuously, scanning and indexing files. This causes noticeable disk and CPU usage, especially after updates or file changes. Disabling it trades slower file search for better overall performance.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Reduced background disk and CPU usage".into(),
            when_not_to_use: "If you frequently search for files and need instant results.".into(),
            how_to_undo: "Re-enable Windows Search service in Services (services.msc).".into(),
            tags: vec!["performance".into(), "disk".into(), "cpu".into(), "search".into()],
            actions: vec![TweakAction::Service {
                name: "WSearch".into(),
                desired_startup: ServiceStartup::Disabled,
            }],
        },
        TweakDefinition {
            id: "disable_error_reporting".into(),
            name: "Disable Windows Error Reporting".into(),
            description: "Stops Windows from collecting and sending crash reports.".into(),
            why_it_helps: "Error Reporting collects crash dumps and sends them to Microsoft. This uses disk space for dump files and network bandwidth for uploads. Most users never benefit from this data.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Less background disk and network usage".into(),
            when_not_to_use: "If you need crash reports for debugging software issues.".into(),
            how_to_undo: "Re-enable WerSvc service in Services (services.msc).".into(),
            tags: vec!["performance".into(), "privacy".into(), "service".into()],
            actions: vec![
                TweakAction::Service {
                    name: "WerSvc".into(),
                    desired_startup: ServiceStartup::Disabled,
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKLM,
                    path: r"SOFTWARE\Microsoft\Windows\Windows Error Reporting".into(),
                    name: "Disabled".into(),
                    desired_value: RegistryValueData::Dword(1),
                },
            ],
        },
        TweakDefinition {
            id: "disable_remote_assistance".into(),
            name: "Disable Remote Assistance".into(),
            description: "Turns off Windows Remote Assistance which allows others to connect to your PC.".into(),
            why_it_helps: "Remote Assistance listens for incoming connections even when not in use. Disabling it closes a potential attack surface and stops its background service.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Improved security, one less background service".into(),
            when_not_to_use: "If you need IT support to remotely connect to your PC.".into(),
            how_to_undo: "Re-enable in System Properties > Remote tab.".into(),
            tags: vec!["performance".into(), "security".into(), "network".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SYSTEM\CurrentControlSet\Control\Remote Assistance".into(),
                name: "fAllowToGetHelp".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "optimize_processor_scheduling".into(),
            name: "Optimize Processor Scheduling".into(),
            description: "Prioritizes foreground applications for CPU time.".into(),
            why_it_helps: "By default, Windows balances CPU time between foreground and background processes. This tweak tells Windows to give more CPU time to the app you're actively using — your game or work application.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Better responsiveness for active applications".into(),
            when_not_to_use: "If you run heavy background tasks (e.g., video encoding while gaming).".into(),
            how_to_undo: "Set Win32PrioritySeparation back to 2 (default) in registry.".into(),
            tags: vec!["performance".into(), "cpu".into(), "scheduling".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SYSTEM\CurrentControlSet\Control\PriorityControl".into(),
                name: "Win32PrioritySeparation".into(),
                desired_value: RegistryValueData::Dword(38),
            }],
        },
        TweakDefinition {
            id: "disable_connected_experiences".into(),
            name: "Disable Connected User Experiences".into(),
            description: "Stops Windows from downloading suggested content and Microsoft consumer features.".into(),
            why_it_helps: "This service downloads promotional content and suggested apps in the background. Disabling it prevents unwanted app installations and reduces network usage.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No surprise app installations, less background network use".into(),
            when_not_to_use: "If you use Microsoft consumer features like suggested content.".into(),
            how_to_undo: "Delete the DisableWindowsConsumerFeatures registry value.".into(),
            tags: vec!["performance".into(), "privacy".into(), "bloatware".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Policies\Microsoft\Windows\CloudContent".into(),
                name: "DisableWindowsConsumerFeatures".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "disable_activity_history".into(),
            name: "Disable Activity History".into(),
            description: "Stops Windows from tracking your app usage and browsing history.".into(),
            why_it_helps: "Activity History tracks which apps you use and when, storing this data locally and optionally syncing it to Microsoft. Disabling it improves privacy and eliminates background tracking overhead.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Improved privacy, less background data collection".into(),
            when_not_to_use: "If you use Timeline or activity sync across devices.".into(),
            how_to_undo: "Re-enable in Windows Settings > Privacy > Activity history.".into(),
            tags: vec!["performance".into(), "privacy".into(), "tracking".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKLM,
                    path: r"SOFTWARE\Policies\Microsoft\Windows\System".into(),
                    name: "EnableActivityFeed".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKLM,
                    path: r"SOFTWARE\Policies\Microsoft\Windows\System".into(),
                    name: "PublishUserActivities".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
        TweakDefinition {
            id: "disable_app_launch_tracking".into(),
            name: "Disable App Launch Tracking".into(),
            description: "Stops Windows from tracking which apps you launch.".into(),
            why_it_helps: "Windows tracks app launches to personalize the Start Menu. Disabling it gives you a small privacy improvement and eliminates unnecessary write operations.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Minor privacy improvement".into(),
            when_not_to_use: "If you want the Start Menu to show your most-used apps.".into(),
            how_to_undo: "Re-enable in Windows Settings > Personalization > Start.".into(),
            tags: vec!["performance".into(), "privacy".into(), "tracking".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced".into(),
                name: "Start_TrackProgs".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_diagnostic_data".into(),
            name: "Disable Diagnostic Data Processing".into(),
            description: "Limits Windows diagnostic data collection beyond the minimum level.".into(),
            why_it_helps: "Windows collects and processes diagnostic data using background services. Limiting this reduces CPU and disk usage from the DiagTrack service.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Reduced background CPU and disk activity".into(),
            when_not_to_use: "If you need Windows diagnostic data for troubleshooting.".into(),
            how_to_undo: "Re-enable DiagTrack service in Services (services.msc).".into(),
            tags: vec!["performance".into(), "privacy".into(), "telemetry".into(), "service".into()],
            actions: vec![TweakAction::Service {
                name: "DiagTrack".into(),
                desired_startup: ServiceStartup::Disabled,
            }],
        },
        TweakDefinition {
            id: "disable_ntfs_last_access".into(),
            name: "Disable NTFS Last Access Timestamp".into(),
            description: "Prevents NTFS from updating the last access timestamp on files.".into(),
            why_it_helps: "Every time a file is read, NTFS writes a timestamp update. Disabling this eliminates millions of unnecessary disk writes, improving I/O throughput on busy systems.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Reduced disk writes, improved I/O performance".into(),
            when_not_to_use: "If you rely on last-access timestamps for auditing or backup software.".into(),
            how_to_undo: "Run: fsutil behavior set disableLastAccess 0".into(),
            tags: vec!["performance".into(), "disk".into(), "ntfs".into()],
            actions: vec![TweakAction::Command {
                apply_cmd: "fsutil behavior set disableLastAccess 1".into(),
                revert_cmd: "fsutil behavior set disableLastAccess 0".into(),
            }],
        },
        TweakDefinition {
            id: "increase_ntfs_memory".into(),
            name: "Increase NTFS Memory Usage".into(),
            description: "Allows NTFS to use more paged pool memory for file system operations.".into(),
            why_it_helps: "Increasing NTFS memory usage lets the file system cache more metadata in RAM, reducing disk reads for file operations and improving throughput on systems with ample memory.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Faster file operations with more metadata caching".into(),
            when_not_to_use: "If your system has limited RAM (4GB or less).".into(),
            how_to_undo: "Delete the NtfsMemoryUsage registry value or set it to 1.".into(),
            tags: vec!["performance".into(), "disk".into(), "ntfs".into(), "memory".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SYSTEM\CurrentControlSet\Control\FileSystem".into(),
                name: "NtfsMemoryUsage".into(),
                desired_value: RegistryValueData::Dword(2),
            }],
        },
        TweakDefinition {
            id: "disable_8dot3_naming".into(),
            name: "Disable 8.3 File Name Creation".into(),
            description: "Stops NTFS from creating legacy short (8.3) file names.".into(),
            why_it_helps: "NTFS creates a DOS-compatible 8.3 short name for every file, which adds overhead to file creation operations. Disabling this speeds up directory enumeration and file creation on volumes with many files.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Faster file creation and directory listing".into(),
            when_not_to_use: "If you run very old 16-bit programs that require 8.3 file names.".into(),
            how_to_undo: "Set NtfsDisable8dot3NameCreation back to 0 in registry.".into(),
            tags: vec!["performance".into(), "disk".into(), "ntfs".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SYSTEM\CurrentControlSet\Control\FileSystem".into(),
                name: "NtfsDisable8dot3NameCreation".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "increase_irp_stack_size".into(),
            name: "Increase IRP Stack Size".into(),
            description: "Increases the I/O Request Packet stack size for the SMB server.".into(),
            why_it_helps: "The default IRP stack size can be insufficient for complex network file operations, causing errors or slowdowns. Increasing it to 32 ensures reliable and faster network file sharing performance.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Advanced,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Improved network file sharing performance".into(),
            when_not_to_use: "If you don't use network file sharing or have a standalone PC.".into(),
            how_to_undo: "Delete the IRPStackSize registry value to restore the default.".into(),
            tags: vec!["performance".into(), "network".into(), "smb".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters".into(),
                name: "IRPStackSize".into(),
                desired_value: RegistryValueData::Dword(32),
            }],
        },
        TweakDefinition {
            id: "optimize_system_responsiveness".into(),
            name: "Optimize System Responsiveness".into(),
            description: "Sets system responsiveness to prioritize multimedia and real-time tasks.".into(),
            why_it_helps: "Windows reserves a percentage of CPU resources for background tasks. Setting SystemResponsiveness to 0 tells Windows to allocate nearly all CPU time to foreground multimedia tasks like gaming and video playback.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Better gaming and multimedia performance".into(),
            when_not_to_use: "If you run important background tasks alongside games or media.".into(),
            how_to_undo: "Set SystemResponsiveness back to 20 (default) in registry.".into(),
            tags: vec!["performance".into(), "cpu".into(), "gaming".into(), "multimedia".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile".into(),
                name: "SystemResponsiveness".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_hibernation".into(),
            name: "Disable Hibernation".into(),
            description: "Disables hibernation and deletes the hiberfil.sys file.".into(),
            why_it_helps: "Hibernation saves your RAM contents to disk, consuming 4-8GB of storage via hiberfil.sys. Disabling it frees this disk space immediately. If you use an SSD, the space savings can be significant.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Frees 4-8GB of disk space".into(),
            when_not_to_use: "If you use hibernation or rely on Fast Startup (which depends on hibernation).".into(),
            how_to_undo: "Run: powercfg /hibernate on".into(),
            tags: vec!["performance".into(), "disk".into(), "space".into()],
            actions: vec![TweakAction::Command {
                apply_cmd: "powercfg /hibernate off".into(),
                revert_cmd: "powercfg /hibernate on".into(),
            }],
        },
        TweakDefinition {
            id: "optimize_visual_for_performance".into(),
            name: "Optimize Visual Effects for Performance".into(),
            description: "Sets Windows visual effects to best performance mode.".into(),
            why_it_helps: "Windows animations, transparency, and visual effects consume GPU and CPU resources. Setting visual effects to best performance disables all unnecessary eye candy, freeing resources for applications.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: true,
            reversible: true,
            impact_estimate: "Faster UI responsiveness, freed GPU/CPU resources".into(),
            when_not_to_use: "If you prefer a polished visual experience with animations and transparency.".into(),
            how_to_undo: "Set VisualFXSetting back to 0 or use System Properties > Advanced > Performance Settings.".into(),
            tags: vec!["performance".into(), "visual".into(), "gpu".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects".into(),
                name: "VisualFXSetting".into(),
                desired_value: RegistryValueData::Dword(2),
            }],
        },
        TweakDefinition {
            id: "disable_cortana".into(),
            name: "Disable Cortana".into(),
            description: "Disables Microsoft Cortana assistant via Group Policy.".into(),
            why_it_helps: "Cortana runs background processes for speech recognition and cloud integration even when not actively used. Disabling it via policy prevents it from starting, freeing memory and CPU cycles.".into(),
            category: TweakCategory::Performance,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Less background CPU and memory usage".into(),
            when_not_to_use: "If you use Cortana for voice commands or reminders.".into(),
            how_to_undo: "Set AllowCortana back to 1 in registry or delete the value.".into(),
            tags: vec!["performance".into(), "cortana".into(), "assistant".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Policies\Microsoft\Windows\Windows Search".into(),
                name: "AllowCortana".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
    ]
}
