use crate::engine::tweak::*;

pub fn tweaks() -> Vec<TweakDefinition> {
    vec![
        TweakDefinition {
            id: "high_performance_power".into(),
            name: "Switch to High Performance Power Plan".into(),
            description: "Activates the built-in High Performance power plan.".into(),
            why_it_helps: "The default 'Balanced' plan throttles CPU and GPU frequencies to save power. High Performance keeps your hardware running at full speed, which directly improves FPS and reduces stutter.".into(),
            category: TweakCategory::Power,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Prevents CPU/GPU throttling, consistent high performance".into(),
            when_not_to_use: "If you're on a laptop and need to conserve battery life.".into(),
            how_to_undo: "Switch back to Balanced in Windows Settings > System > Power & battery.".into(),
            tags: vec!["power".into(), "cpu".into(), "gpu".into(), "battery".into()],
            actions: vec![TweakAction::PowerPlan {
                guid: "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c".into(),
            }],
        },
        TweakDefinition {
            id: "ultimate_performance_power".into(),
            name: "Switch to Ultimate Performance Power Plan".into(),
            description: "Activates or creates the Ultimate Performance power plan.".into(),
            why_it_helps: "Ultimate Performance goes beyond High Performance by eliminating micro-latencies in power management. It's designed for workstations but provides the absolute best performance for gaming too. Uses more electricity.".into(),
            category: TweakCategory::Power,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Maximum CPU/GPU performance, no power-saving throttling".into(),
            when_not_to_use: "If you're on a laptop, or your electricity costs are a concern.".into(),
            how_to_undo: "Switch back to Balanced in Windows Settings > System > Power & battery.".into(),
            tags: vec!["power".into(), "cpu".into(), "gpu".into(), "maximum".into()],
            actions: vec![
                TweakAction::Command {
                    apply_cmd: "powercfg /duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61 2>nul & powercfg /setactive e9a42b02-d5df-448d-aa00-03f14749eb61".into(),
                    revert_cmd: "powercfg /setactive 381b4222-f694-41f0-9685-ff5bb260df2e".into(),
                },
            ],
        },
        TweakDefinition {
            id: "balanced_power_plan".into(),
            name: "Switch to Balanced Power Plan".into(),
            description: "Activates the built-in Balanced power plan.".into(),
            why_it_helps: "The Balanced plan dynamically adjusts CPU speed based on demand, providing good performance when needed while saving energy at idle. It's the best default for most users.".into(),
            category: TweakCategory::Power,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Good balance of performance and power efficiency".into(),
            when_not_to_use: "If you need maximum performance at all times for gaming or workloads.".into(),
            how_to_undo: "Switch to a different power plan in Windows Settings > System > Power.".into(),
            tags: vec!["power".into(), "balanced".into(), "default".into()],
            actions: vec![TweakAction::PowerPlan {
                guid: "381b4222-f694-41f0-9685-ff5bb260df2e".into(),
            }],
        },
        TweakDefinition {
            id: "power_saver_plan".into(),
            name: "Switch to Power Saver Plan".into(),
            description: "Activates the built-in Power Saver power plan.".into(),
            why_it_helps: "The Power Saver plan aggressively reduces CPU speed and dims the display to minimize power consumption. Ideal for extending laptop battery life when performance isn't critical.".into(),
            category: TweakCategory::Power,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Maximum battery life, reduced power consumption".into(),
            when_not_to_use: "If you need decent performance — this plan will noticeably slow your PC.".into(),
            how_to_undo: "Switch to Balanced in Windows Settings > System > Power & battery.".into(),
            tags: vec!["power".into(), "battery".into(), "saver".into()],
            actions: vec![TweakAction::PowerPlan {
                guid: "a1841308-3541-4fab-bc81-f71556f20b4a".into(),
            }],
        },
        TweakDefinition {
            id: "processor_max_100".into(),
            name: "Set Max Processor State to 100%".into(),
            description: "Ensures the CPU can run at its full rated speed.".into(),
            why_it_helps: "Some power plans limit the maximum CPU frequency to save power. Setting it to 100% ensures your processor can reach its full turbo speed, providing the best possible performance for demanding tasks.".into(),
            category: TweakCategory::Power,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Full CPU performance available when needed".into(),
            when_not_to_use: "If you need to limit CPU speed to reduce heat or noise on a laptop.".into(),
            how_to_undo: "Adjust maximum processor state in Power Options > Advanced settings.".into(),
            tags: vec!["power".into(), "cpu".into(), "performance".into()],
            actions: vec![TweakAction::Command {
                apply_cmd: "powercfg -setacvalueindex SCHEME_CURRENT SUB_PROCESSOR PROCTHROTTLEMAX 100 & powercfg -setactive SCHEME_CURRENT".into(),
                revert_cmd: "powercfg -setacvalueindex SCHEME_CURRENT SUB_PROCESSOR PROCTHROTTLEMAX 100 & powercfg -setactive SCHEME_CURRENT".into(),
            }],
        },
        TweakDefinition {
            id: "disable_usb_suspend".into(),
            name: "Disable USB Selective Suspend".into(),
            description: "Prevents Windows from powering down USB devices to save energy.".into(),
            why_it_helps: "USB selective suspend can cause USB devices to disconnect or lag when waking from a suspended state. Disabling it ensures peripherals like gaming mice, keyboards, and audio devices stay responsive at all times.".into(),
            category: TweakCategory::Power,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "More reliable USB device behavior, no disconnects".into(),
            when_not_to_use: "If you're on a laptop and need to conserve battery life.".into(),
            how_to_undo: "Set DisableSelectiveSuspend back to 0 in registry.".into(),
            tags: vec!["power".into(), "usb".into(), "peripherals".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SYSTEM\CurrentControlSet\Services\USB".into(),
                name: "DisableSelectiveSuspend".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "aggressive_cooling".into(),
            name: "Set Active Cooling Policy".into(),
            description: "Sets the cooling policy to active, running fans at higher speed before throttling CPU.".into(),
            why_it_helps: "Windows can choose between passive cooling (throttle CPU first, then spin fans) or active cooling (spin fans first, then throttle). Active cooling keeps your CPU at full speed longer by using fans more aggressively.".into(),
            category: TweakCategory::Power,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Better sustained CPU performance under load".into(),
            when_not_to_use: "If fan noise bothers you or you prefer quieter operation.".into(),
            how_to_undo: "Run: powercfg -setacvalueindex SCHEME_CURRENT SUB_PROCESSOR SYSCOOLPOL 0 & powercfg -setactive SCHEME_CURRENT".into(),
            tags: vec!["power".into(), "cpu".into(), "cooling".into(), "fans".into()],
            actions: vec![TweakAction::Command {
                apply_cmd: "powercfg -setacvalueindex SCHEME_CURRENT SUB_PROCESSOR SYSCOOLPOL 1 & powercfg -setactive SCHEME_CURRENT".into(),
                revert_cmd: "powercfg -setacvalueindex SCHEME_CURRENT SUB_PROCESSOR SYSCOOLPOL 0 & powercfg -setactive SCHEME_CURRENT".into(),
            }],
        },
        TweakDefinition {
            id: "disable_lid_close_sleep".into(),
            name: "Prevent Sleep on Lid Close".into(),
            description: "Prevents the laptop from sleeping when the lid is closed while on AC power.".into(),
            why_it_helps: "Closing a laptop lid normally triggers sleep, interrupting downloads, renders, or other long-running tasks. Disabling this lets your laptop keep running with the lid closed, useful for docked or external-monitor setups.".into(),
            category: TweakCategory::Power,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Laptop stays active with lid closed".into(),
            when_not_to_use: "If you want your laptop to sleep when you close it.".into(),
            how_to_undo: "Run: powercfg -setacvalueindex SCHEME_CURRENT SUB_BUTTONS LIDACTION 1 & powercfg -setactive SCHEME_CURRENT".into(),
            tags: vec!["power".into(), "laptop".into(), "lid".into(), "sleep".into()],
            actions: vec![TweakAction::Command {
                apply_cmd: "powercfg -setacvalueindex SCHEME_CURRENT SUB_BUTTONS LIDACTION 0 & powercfg -setactive SCHEME_CURRENT".into(),
                revert_cmd: "powercfg -setacvalueindex SCHEME_CURRENT SUB_BUTTONS LIDACTION 1 & powercfg -setactive SCHEME_CURRENT".into(),
            }],
        },
        TweakDefinition {
            id: "never_sleep_plugged_in".into(),
            name: "Never Sleep When Plugged In".into(),
            description: "Prevents the PC from automatically entering sleep mode when on AC power.".into(),
            why_it_helps: "Automatic sleep can interrupt long-running tasks like downloads, builds, or renders. Setting the AC sleep timeout to 0 (never) keeps your PC awake indefinitely when plugged in.".into(),
            category: TweakCategory::Power,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "PC stays awake for long-running tasks".into(),
            when_not_to_use: "If you forget to manually put your PC to sleep and want to save power.".into(),
            how_to_undo: "Run: powercfg -change -standby-timeout-ac 30".into(),
            tags: vec!["power".into(), "sleep".into(), "always-on".into()],
            actions: vec![TweakAction::Command {
                apply_cmd: "powercfg -change -standby-timeout-ac 0".into(),
                revert_cmd: "powercfg -change -standby-timeout-ac 30".into(),
            }],
        },
        TweakDefinition {
            id: "never_turn_off_display".into(),
            name: "Never Turn Off Display on AC".into(),
            description: "Prevents the display from automatically turning off when on AC power.".into(),
            why_it_helps: "Auto display-off can be annoying during presentations, long reads, or monitoring tasks. Setting the timeout to 0 keeps your screen on indefinitely when plugged in.".into(),
            category: TweakCategory::Power,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Display stays on for uninterrupted use".into(),
            when_not_to_use: "If you want to save energy and extend your monitor's lifespan.".into(),
            how_to_undo: "Run: powercfg -change -monitor-timeout-ac 10".into(),
            tags: vec!["power".into(), "display".into(), "always-on".into()],
            actions: vec![TweakAction::Command {
                apply_cmd: "powercfg -change -monitor-timeout-ac 0".into(),
                revert_cmd: "powercfg -change -monitor-timeout-ac 10".into(),
            }],
        },
    ]
}
