use crate::engine::tweak::*;

pub fn tweaks() -> Vec<TweakDefinition> {
    vec![
        TweakDefinition {
            id: "disable_advertising_id".into(),
            name: "Disable Advertising ID".into(),
            description: "Prevents Windows from using a unique advertising ID for targeted ads.".into(),
            why_it_helps: "Stops apps and advertisers from tracking you with a unique identifier tied to your Microsoft account.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No performance impact, reduces ad tracking".into(),
            when_not_to_use: "If you prefer personalized ads in apps.".into(),
            how_to_undo: "Settings > Privacy > General > Let apps use advertising ID.".into(),
            tags: vec!["privacy".into(), "advertising".into(), "tracking".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo".into(),
                name: "Enabled".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_activity_history".into(),
            name: "Disable Activity History".into(),
            description: "Stops Windows from collecting your activity history.".into(),
            why_it_helps: "Prevents Windows from storing and syncing your app usage, browsing history, and file activity.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No performance impact, reduces data collection".into(),
            when_not_to_use: "If you use Timeline or activity sync across devices.".into(),
            how_to_undo: "Settings > Privacy > Activity History.".into(),
            tags: vec!["privacy".into(), "tracking".into(), "data".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKLM,
                    path: r"SOFTWARE\Policies\Microsoft\Windows\System".into(),
                    name: "EnableActivityFeed".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKLM,
                    path: r"SOFTWARE\Policies\Microsoft\Windows\System".into(),
                    name: "PublishUserActivities".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKLM,
                    path: r"SOFTWARE\Policies\Microsoft\Windows\System".into(),
                    name: "UploadUserActivities".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
        TweakDefinition {
            id: "reduce_telemetry".into(),
            name: "Reduce Telemetry to Minimum".into(),
            description: "Sets Windows diagnostic data collection to the minimum required level.".into(),
            why_it_helps: "Reduces the amount of usage data Windows sends to Microsoft while keeping required functionality intact.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Slight reduction in background data upload".into(),
            when_not_to_use: "If you want to help Microsoft improve Windows with detailed diagnostics.".into(),
            how_to_undo: "Settings > Privacy > Diagnostics & Feedback.".into(),
            tags: vec!["privacy".into(), "telemetry".into(), "data".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Policies\Microsoft\Windows\DataCollection".into(),
                name: "AllowTelemetry".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "disable_location_tracking".into(),
            name: "Disable Location Tracking".into(),
            description: "Disables Windows location services for all apps.".into(),
            why_it_helps: "Prevents apps and Windows from accessing your physical location.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No performance impact".into(),
            when_not_to_use: "If you use Maps, Weather, or location-based apps.".into(),
            how_to_undo: "Settings > Privacy > Location.".into(),
            tags: vec!["privacy".into(), "location".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Policies\Microsoft\Windows\LocationAndSensors".into(),
                name: "DisableLocation".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "disable_app_launch_tracking".into(),
            name: "Disable App Launch Tracking".into(),
            description: "Stops Windows from tracking which apps you launch.".into(),
            why_it_helps: "Prevents Windows from monitoring and recording your app usage patterns.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No performance impact".into(),
            when_not_to_use: "If you rely on Most Used apps in Start menu.".into(),
            how_to_undo: "Re-enable in registry: Start_TrackProgs = 1.".into(),
            tags: vec!["privacy".into(), "tracking".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced".into(),
                name: "Start_TrackProgs".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_tailored_experiences".into(),
            name: "Disable Tailored Experiences".into(),
            description: "Stops Microsoft from using your diagnostic data to personalize tips and recommendations.".into(),
            why_it_helps: "Prevents Microsoft from using your data to show targeted suggestions and ads.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No performance impact".into(),
            when_not_to_use: "If you find Microsoft's personalized suggestions helpful.".into(),
            how_to_undo: "Settings > Privacy > Diagnostics & Feedback > Tailored experiences.".into(),
            tags: vec!["privacy".into(), "advertising".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Privacy".into(),
                name: "TailoredExperiencesWithDiagnosticDataEnabled".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_speech_recognition".into(),
            name: "Disable Online Speech Recognition".into(),
            description: "Disables cloud-based speech recognition services.".into(),
            why_it_helps: "Prevents your voice data from being sent to Microsoft for processing.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No performance impact".into(),
            when_not_to_use: "If you use Cortana or voice dictation.".into(),
            how_to_undo: "Settings > Privacy > Speech.".into(),
            tags: vec!["privacy".into(), "data".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Speech_OneCore\Settings\OnlineSpeechPrivacy".into(),
                name: "HasAccepted".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_inking_personalization".into(),
            name: "Disable Inking & Typing Personalization".into(),
            description: "Stops Windows from learning your typing and inking patterns.".into(),
            why_it_helps: "Prevents Windows from collecting your typing patterns and handwriting data.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No performance impact".into(),
            when_not_to_use: "If you use pen input or want better autocorrect.".into(),
            how_to_undo: "Settings > Privacy > Inking & Typing Personalization.".into(),
            tags: vec!["privacy".into(), "data".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\InputPersonalization".into(),
                    name: "RestrictImplicitInkCollection".into(),
                    desired_value: RegistryValueData::Dword(1),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\InputPersonalization".into(),
                    name: "RestrictImplicitTextCollection".into(),
                    desired_value: RegistryValueData::Dword(1),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Personalization\Settings".into(),
                    name: "AcceptedPrivacyPolicy".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
        TweakDefinition {
            id: "disable_clipboard_history".into(),
            name: "Disable Clipboard History".into(),
            description: "Turns off Windows clipboard history that stores copied items.".into(),
            why_it_helps: "Prevents Windows from storing a history of everything you copy, which could include sensitive data.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No performance impact".into(),
            when_not_to_use: "If you use Win+V clipboard history regularly.".into(),
            how_to_undo: "Settings > System > Clipboard > Clipboard history.".into(),
            tags: vec!["privacy".into(), "data".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Clipboard".into(),
                name: "EnableClipboardHistory".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_diagnostic_data_viewer".into(),
            name: "Disable Diagnostic Data Viewer".into(),
            description: "Disables the diagnostic data viewer service.".into(),
            why_it_helps: "Reduces a background service that stores and displays diagnostic data locally.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Minor RAM savings".into(),
            when_not_to_use: "If you actively review diagnostic data.".into(),
            how_to_undo: "Settings > Privacy > Diagnostics & Feedback.".into(),
            tags: vec!["privacy".into(), "diagnostics".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Policies\Microsoft\Windows\DataCollection".into(),
                name: "DisableDiagnosticDataViewer".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "disable_suggested_content_settings".into(),
            name: "Disable Suggested Content in Settings".into(),
            description: "Removes Microsoft suggestions and tips from the Settings app.".into(),
            why_it_helps: "Stops Microsoft from showing promotional content inside Windows Settings.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No performance impact".into(),
            when_not_to_use: "Never, this is purely cosmetic.".into(),
            how_to_undo: "Settings > Privacy > General.".into(),
            tags: vec!["privacy".into(), "advertising".into(), "annoyance".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager".into(),
                    name: "SubscribedContent-338393Enabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager".into(),
                    name: "SubscribedContent-353694Enabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager".into(),
                    name: "SubscribedContent-353696Enabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
        TweakDefinition {
            id: "disable_app_diagnostics".into(),
            name: "Disable App Diagnostics Access".into(),
            description: "Prevents apps from accessing diagnostic information about other apps.".into(),
            why_it_helps: "Stops apps from seeing what other apps are running and their resource usage.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No performance impact".into(),
            when_not_to_use: "If you use diagnostic or monitoring apps that need this access.".into(),
            how_to_undo: "Settings > Privacy > App diagnostics.".into(),
            tags: vec!["privacy".into(), "diagnostics".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\DeviceAccess\Global\{2297E4E2-5DBE-466D-A12B-0F8286F0D9CA}".into(),
                name: "Value".into(),
                desired_value: RegistryValueData::String("Deny".into()),
            }],
        },
        TweakDefinition {
            id: "disable_wifi_sense".into(),
            name: "Disable Wi-Fi Sense".into(),
            description: "Prevents Windows from sharing Wi-Fi credentials and connecting to suggested networks.".into(),
            why_it_helps: "Stops Windows from automatically connecting to open hotspots and sharing your Wi-Fi passwords.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No performance impact, improves security".into(),
            when_not_to_use: "If you rely on automatic Wi-Fi hotspot connections.".into(),
            how_to_undo: "Settings > Network > Wi-Fi > Wi-Fi Sense.".into(),
            tags: vec!["privacy".into(), "network".into(), "security".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKLM,
                    path: r"SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\config".into(),
                    name: "AutoConnectAllowedOEM".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
        TweakDefinition {
            id: "disable_handwriting_error_reports".into(),
            name: "Disable Handwriting Error Reports".into(),
            description: "Stops Windows from sending handwriting recognition error data.".into(),
            why_it_helps: "Prevents handwriting data from being sent to Microsoft for analysis.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No performance impact".into(),
            when_not_to_use: "If you use pen input and want improved recognition.".into(),
            how_to_undo: "Set PreventHandwritingErrorReports back to 0 in registry.".into(),
            tags: vec!["privacy".into(), "data".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Policies\Microsoft\Windows\HandwritingErrorReports".into(),
                name: "PreventHandwritingErrorReports".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "disable_inventory_collector".into(),
            name: "Disable Inventory Collector".into(),
            description: "Disables the Windows inventory collector that sends app data to Microsoft.".into(),
            why_it_helps: "Prevents Windows from inventorying your installed apps and sending the data to Microsoft.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Minor reduction in background activity".into(),
            when_not_to_use: "If your organization requires application inventory.".into(),
            how_to_undo: "Set DisableInventory back to 0 in registry.".into(),
            tags: vec!["privacy".into(), "telemetry".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Policies\Microsoft\Windows\AppCompat".into(),
                name: "DisableInventory".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "disable_ad_personalization".into(),
            name: "Disable Ad Personalization".into(),
            description: "Opts out of personalized advertising across Windows.".into(),
            why_it_helps: "Tells Microsoft not to use your data to personalize ads in apps and websites.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No performance impact".into(),
            when_not_to_use: "If you prefer ads relevant to your interests.".into(),
            how_to_undo: "Settings > Privacy > General.".into(),
            tags: vec!["privacy".into(), "advertising".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo".into(),
                    name: "Enabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\CPSS\Store\AdvertisingInfo".into(),
                    name: "Value".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
        TweakDefinition {
            id: "disable_website_language_list".into(),
            name: "Disable Website Language List Access".into(),
            description: "Prevents websites from accessing your language list for content targeting.".into(),
            why_it_helps: "Reduces your browser fingerprint by not sharing your installed language list.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No performance impact".into(),
            when_not_to_use: "If you want websites to automatically show content in your preferred language.".into(),
            how_to_undo: "Settings > Privacy > General.".into(),
            tags: vec!["privacy".into(), "tracking".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"Control Panel\International\User Profile".into(),
                name: "HttpAcceptLanguageOptOut".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "disable_settings_sync".into(),
            name: "Disable Settings Sync".into(),
            description: "Stops Windows from syncing your settings across devices.".into(),
            why_it_helps: "Prevents your personalization data, passwords, and preferences from being synced through Microsoft's cloud.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No performance impact".into(),
            when_not_to_use: "If you use multiple Windows devices and want settings to sync.".into(),
            how_to_undo: "Settings > Accounts > Sync your settings.".into(),
            tags: vec!["privacy".into(), "data".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Personalization".into(),
                name: "Enabled".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_customer_experience".into(),
            name: "Disable Customer Experience Improvement".into(),
            description: "Opts out of the Windows Customer Experience Improvement Program.".into(),
            why_it_helps: "Stops Windows from collecting and sending usage data for the CEIP program.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Minor reduction in background data collection".into(),
            when_not_to_use: "If you want to help Microsoft improve Windows.".into(),
            how_to_undo: "Set CEIPEnable back to 1 in registry.".into(),
            tags: vec!["privacy".into(), "telemetry".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Policies\Microsoft\SQMClient\Windows".into(),
                name: "CEIPEnable".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_app_suggestions_privacy".into(),
            name: "Disable App Suggestions & Content Delivery".into(),
            description: "Prevents Windows from suggesting apps and delivering promotional content.".into(),
            why_it_helps: "Stops Microsoft from installing suggested apps and showing promotional content.".into(),
            category: TweakCategory::Privacy,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "No performance impact, cleaner experience".into(),
            when_not_to_use: "If you want app suggestions from Microsoft.".into(),
            how_to_undo: "Settings > Personalization > Start > Show suggestions.".into(),
            tags: vec!["privacy".into(), "advertising".into(), "annoyance".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager".into(),
                    name: "SilentInstalledAppsEnabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager".into(),
                    name: "SystemPaneSuggestionsEnabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager".into(),
                    name: "SoftLandingEnabled".into(),
                    desired_value: RegistryValueData::Dword(0),
                },
            ],
        },
    ]
}
