use crate::engine::tweak::*;

pub fn tweaks() -> Vec<TweakDefinition> {
    vec![
        TweakDefinition {
            id: "disable_startup_delay".into(),
            name: "Disable Startup Delay".into(),
            description: "Removes the artificial delay Windows adds before launching startup apps.".into(),
            why_it_helps: "Windows intentionally delays startup programs by up to 10 seconds to make the desktop feel responsive faster. Removing this delay lets startup apps launch immediately, which can actually speed up your overall boot-to-ready time.".into(),
            category: TweakCategory::Startup,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: true,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Faster boot-to-ready time".into(),
            when_not_to_use: "If your PC struggles during boot and you want a responsive desktop faster.".into(),
            how_to_undo: "Delete the StartupDelayInMSec registry value.".into(),
            tags: vec!["startup".into(), "boot".into(), "speed".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Serialize".into(),
                name: "StartupDelayInMSec".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "reduce_login_delay".into(),
            name: "Reduce Startup Login Delay".into(),
            description: "Reduces the desktop switch timeout during login.".into(),
            why_it_helps: "Windows adds a delay when switching from the lock screen to the desktop. Setting DelayedDesktopSwitchTimeout to 0 eliminates this pause, getting you to your desktop faster after login.".into(),
            category: TweakCategory::Startup,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Faster login-to-desktop transition".into(),
            when_not_to_use: "If you experience display issues during login.".into(),
            how_to_undo: "Delete the DelayedDesktopSwitchTimeout registry value.".into(),
            tags: vec!["startup".into(), "boot".into(), "login".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System".into(),
                name: "DelayedDesktopSwitchTimeout".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_startup_programs_delay".into(),
            name: "Disable Startup Programs Delay".into(),
            description: "Eliminates the built-in delay before launching startup programs.".into(),
            why_it_helps: "Windows adds a configurable delay (default ~10 seconds) before running startup programs to prioritize system services. Setting this to 0 lets your apps start immediately, reducing total boot-to-ready time.".into(),
            category: TweakCategory::Startup,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: true,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Startup programs launch immediately".into(),
            when_not_to_use: "If your PC is slow during boot and you need the desktop responsive first.".into(),
            how_to_undo: "Delete the StartupDelayInMSec registry value or set it to 10000.".into(),
            tags: vec!["startup".into(), "boot".into(), "speed".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Serialize".into(),
                name: "StartupDelayInMSec".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "fast_startup_enable".into(),
            name: "Enable Windows Fast Startup".into(),
            description: "Enables Windows Fast Startup (hybrid boot) for quicker cold boots.".into(),
            why_it_helps: "Fast Startup saves the kernel session to disk on shutdown, allowing Windows to resume from this image on the next boot. This significantly reduces cold boot time, often cutting it in half.".into(),
            category: TweakCategory::Startup,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Recommended,
            requires_reboot: true,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Significantly faster cold boot times".into(),
            when_not_to_use: "If you dual-boot with Linux or need a full clean shutdown every time.".into(),
            how_to_undo: "Set HiberbootEnabled back to 0 in registry.".into(),
            tags: vec!["startup".into(), "boot".into(), "fast".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SYSTEM\CurrentControlSet\Control\Session Manager\Power".into(),
                name: "HiberbootEnabled".into(),
                desired_value: RegistryValueData::Dword(1),
            }],
        },
        TweakDefinition {
            id: "defer_windows_updates_startup".into(),
            name: "Defer Windows Updates During Startup".into(),
            description: "Configures Windows Update to notify before downloading, preventing update activity during startup.".into(),
            why_it_helps: "By default, Windows Update downloads and installs updates automatically, which can slow down startup and consume bandwidth. Setting AUOptions to 2 (notify before download) prevents this from impacting boot performance.".into(),
            category: TweakCategory::Startup,
            risk_level: RiskLevel::Moderate,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: true,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Faster startups without update interference".into(),
            when_not_to_use: "If you want updates to install automatically for security.".into(),
            how_to_undo: "Delete the AUOptions registry value to restore automatic updates.".into(),
            tags: vec!["startup".into(), "updates".into(), "boot".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKLM,
                path: r"SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU".into(),
                name: "AUOptions".into(),
                desired_value: RegistryValueData::Dword(2),
            }],
        },
    ]
}
