use crate::engine::tweak::*;

pub fn tweaks() -> Vec<TweakDefinition> {
    vec![
        TweakDefinition {
            id: "disable_transparency".into(),
            name: "Disable Transparency Effects".into(),
            description: "Turns off the transparent/blur effect on the taskbar, Start Menu, and windows.".into(),
            why_it_helps: "Transparency effects require GPU compositing, which uses GPU resources that could go to your game. Disabling them frees up GPU overhead and can improve FPS on lower-end hardware.".into(),
            category: TweakCategory::Visual,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Slight GPU improvement, especially on integrated graphics".into(),
            when_not_to_use: "If you prefer the look of transparent taskbar and windows.".into(),
            how_to_undo: "Re-enable in Windows Settings > Personalization > Colors.".into(),
            tags: vec!["visual".into(), "gpu".into(), "transparency".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize".into(),
                name: "EnableTransparency".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_animations".into(),
            name: "Disable Window Animations".into(),
            description: "Turns off window open/close/minimize animations.".into(),
            why_it_helps: "Animations add visual delay to every window operation. Disabling them makes the OS feel snappier and more responsive, especially on lower-end hardware.".into(),
            category: TweakCategory::Visual,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Snappier window operations, reduced GPU load".into(),
            when_not_to_use: "If you prefer smooth window transitions and don't mind the small delay.".into(),
            how_to_undo: "Re-enable in System Properties > Advanced > Performance Settings.".into(),
            tags: vec!["visual".into(), "gpu".into(), "animations".into(), "responsiveness".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"Control Panel\Desktop\WindowMetrics".into(),
                    name: "MinAnimate".into(),
                    desired_value: RegistryValueData::String("0".into()),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"Control Panel\Desktop".into(),
                    name: "MenuShowDelay".into(),
                    desired_value: RegistryValueData::String("0".into()),
                },
            ],
        },
        TweakDefinition {
            id: "disable_shadows".into(),
            name: "Disable Window Shadows".into(),
            description: "Removes drop shadows under windows and menus.".into(),
            why_it_helps: "Shadow rendering uses GPU resources for a purely cosmetic effect. Disabling shadows can slightly improve performance on systems with limited GPU power.".into(),
            category: TweakCategory::Visual,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Advanced,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Minor GPU improvement, less visual polish".into(),
            when_not_to_use: "If you value the visual depth that shadows provide.".into(),
            how_to_undo: "Re-enable in System Properties > Advanced > Performance Settings.".into(),
            tags: vec!["visual".into(), "gpu".into(), "shadows".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced".into(),
                name: "ListviewShadow".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_smooth_scrolling".into(),
            name: "Disable Smooth Scrolling".into(),
            description: "Turns off smooth scrolling animations in windows and browsers.".into(),
            why_it_helps: "Smooth scrolling adds interpolation frames between scroll positions. Disabling it makes scrolling instant and can feel more responsive, though some users prefer the smooth look.".into(),
            category: TweakCategory::Visual,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Advanced,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "More responsive scrolling".into(),
            when_not_to_use: "If you prefer the smooth scrolling visual experience.".into(),
            how_to_undo: "Delete the SmoothScroll registry value.".into(),
            tags: vec!["visual".into(), "scrolling".into(), "responsiveness".into()],
            actions: vec![TweakAction::Registry {
                hive: RegistryHive::HKCU,
                path: r"Control Panel\Desktop".into(),
                name: "SmoothScroll".into(),
                desired_value: RegistryValueData::Dword(0),
            }],
        },
        TweakDefinition {
            id: "disable_fade_effects".into(),
            name: "Disable Fade Effects".into(),
            description: "Turns off fade-in/fade-out effects for menus and tooltips.".into(),
            why_it_helps: "Fade effects add a short delay before menus and tooltips fully appear. Disabling them makes these elements appear instantly.".into(),
            category: TweakCategory::Visual,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Advanced,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Instant menu and tooltip display".into(),
            when_not_to_use: "If you prefer gradual menu and tooltip appearances.".into(),
            how_to_undo: "Re-enable in System Properties > Advanced > Performance Settings.".into(),
            tags: vec!["visual".into(), "gpu".into(), "menus".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"Control Panel\Desktop".into(),
                    name: "UserPreferencesMask".into(),
                    desired_value: RegistryValueData::Binary(vec![
                        0x90, 0x12, 0x03, 0x80, 0x10, 0x00, 0x00, 0x00,
                    ]),
                },
            ],
        },
        TweakDefinition {
            id: "disable_aero_peek".into(),
            name: "Disable Aero Peek & Shake".into(),
            description: "Turns off the Aero Peek preview and Aero Shake minimize features.".into(),
            why_it_helps: "Aero Peek shows desktop previews when hovering over the taskbar corner. Aero Shake minimizes all other windows when you shake one. Both can be accidentally triggered and are distracting.".into(),
            category: TweakCategory::Visual,
            risk_level: RiskLevel::Safe,
            recommendation: Recommendation::Optional,
            requires_reboot: false,
            requires_admin: false,
            requires_signout: false,
            reversible: true,
            impact_estimate: "Fewer accidental window actions".into(),
            when_not_to_use: "If you use Aero Peek to preview the desktop or Shake to minimize.".into(),
            how_to_undo: "Re-enable in Taskbar settings and System Properties > Advanced.".into(),
            tags: vec!["visual".into(), "desktop".into(), "window-management".into()],
            actions: vec![
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced".into(),
                    name: "DisablePreviewDesktop".into(),
                    desired_value: RegistryValueData::Dword(1),
                },
                TweakAction::Registry {
                    hive: RegistryHive::HKCU,
                    path: r"SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced".into(),
                    name: "DisallowShaking".into(),
                    desired_value: RegistryValueData::Dword(1),
                },
            ],
        },
    ]
}
